# database.py

# ========================================
# DATABASE – 70+ SKJULTE PERLER (MED KARTKOORDINATER)
# ========================================
SKJULTE_PERLER = [
    # ========== SVERIGE ==========
    {"navn": "Torsby Fordonsmuseum", "land": "Sverige", "by": "Torsby", "type": "museum", "beskrivelse": "Ankans eget bilmuseum.", "tips": "Ta en fika med Ankan.", "beste_tid": "hele året", "latitude": 60.1388, "longitude": 13.0119},
    {"navn": "Håveruds akvedukt", "land": "Sverige", "by": "Håverud", "type": "arkitektur", "beskrivelse": "Bro der båter går over veien.", "tips": "Stå under bron.", "beste_tid": "mai-september", "latitude": 58.8222, "longitude": 12.4131},
    {"navn": "Borgvattnets Prästgård", "land": "Sverige", "by": "Borgvattnet", "type": "overnaturlig", "beskrivelse": "Sveriges mest hemsökta hus.", "tips": "Boka övernattning.", "beste_tid": "hele året", "latitude": 63.4211, "longitude": 15.8544},
    {"navn": "Gropens bilkyrkogård", "land": "Sverige", "by": "Ryd", "type": "urbanexploring", "beskrivelse": "Naturen tar tilbake 50-tallsbiler.", "tips": "Fotografer i morgonljus.", "beste_tid": "mai-september", "latitude": 56.4647, "longitude": 14.6547},
    {"navn": "Nämforsens hällristningar", "land": "Sverige", "by": "Näsåker", "type": "historie", "beskrivelse": "2600 helleristninger.", "tips": "Guidet tur ved solnedgang.", "beste_tid": "mai-september", "latitude": 63.4414, "longitude": 16.8858},
    {"navn": "Bjuröklubb", "land": "Sverige", "by": "Lövånger", "type": "natur", "beskrivelse": "Fyr med midnattssol.", "tips": "Bo i fyrvaktarbostaden.", "beste_tid": "juni-juli", "latitude": 64.4811, "longitude": 21.5714},
    {"navn": "Skuleskogen", "land": "Sverige", "by": "Docksta", "type": "natur", "beskrivelse": "Trollskog med 40 m dyp klyfta.", "tips": "Gå Slåttdalsskrevan.", "beste_tid": "mai-september", "latitude": 63.1194, "longitude": 18.4917},
    {"navn": "Ales stenar", "land": "Sverige", "by": "Kåseberga", "type": "historie", "beskrivelse": "Sveriges Stonehenge.", "tips": "Soluppgång med kaffe.", "beste_tid": "hele året", "latitude": 55.3828, "longitude": 14.0544},
    {"navn": "Sarek nasjonalpark", "land": "Sverige", "by": "Jokkmokk", "type": "natur", "beskrivelse": "Europas siste villmark.", "tips": "Kun for erfarne.", "beste_tid": "juli-august", "latitude": 67.2833, "longitude": 17.5333},
    # ========== NORGE ==========
    {"navn": "Pyramiden", "land": "Norge", "by": "Svalbard", "type": "spøkstad", "beskrivelse": "Forlatt sovjetisk gruveby.", "tips": "Guidet tur fra Longyearbyen.", "beste_tid": "juni-august", "latitude": 78.6564, "longitude": 16.3244},
    {"navn": "Røros", "land": "Norge", "by": "Røros", "type": "kultur", "beskrivelse": "UNESCO gruveby frosset i tid.", "tips": "Rømmegrøt på Kaffestuggu.", "beste_tid": "februar, juli", "latitude": 62.5747, "longitude": 11.3842},
    {"navn": "Urnes stavkirke", "land": "Norge", "by": "Urnes", "type": "historie", "beskrivelse": "Norges eldste stavkirke.", "tips": "Ta fergen over Lustrafjorden.", "beste_tid": "mai-september", "latitude": 61.2981, "longitude": 7.3222},
    # ========== DANMARK ==========
    {"navn": "Rubjerg Knude Fyr", "land": "Danmark", "by": "Løkken", "type": "natur", "beskrivelse": "Fyr begravd i sanddyner.", "tips": "Besøk før det faller i havet.", "beste_tid": "hele året", "latitude": 57.4485, "longitude": 9.7749},
    {"navn": "Christiania", "land": "Danmark", "by": "København", "type": "kultur", "beskrivelse": "Selvstyrende fristad.", "tips": "Guidet tur med lokal.", "beste_tid": "hele året", "latitude": 55.6733, "longitude": 12.5997},
    # ========== FINLAND ==========
    {"navn": "Klippekirken", "land": "Finland", "by": "Helsinki", "type": "arkitektur", "beskrivelse": "Kirke uthugget i berget.", "tips": "Gå på konsert.", "beste_tid": "hele året", "latitude": 60.1731, "longitude": 24.9253},
    {"navn": "Bomarsunds festning", "land": "Finland", "by": "Åland", "type": "historie", "beskrivelse": "Russisk festningsruin.", "tips": "Sykkel rundt øyene.", "beste_tid": "mai-september", "latitude": 60.2125, "longitude": 20.2378},
    # ========== TYSKLAND ==========
    {"navn": "Rakotzbrücke", "land": "Tyskland", "by": "Kromlau", "type": "arkitektur", "beskrivelse": "Perfekt sirkelbro.", "tips": "Speilbilde ved soloppgang.", "beste_tid": "mai-oktober", "latitude": 51.5363, "longitude": 14.6405},
    {"navn": "Görlitz", "land": "Tyskland", "by": "Görlitz", "type": "kultur", "beskrivelse": "Tysklands best bevarte by.", "tips": "Peterskirche ved solnedgang.", "beste_tid": "mai-september", "latitude": 51.1528, "longitude": 14.9872},
    {"navn": "Beelitz-Heilstätten", "land": "Tyskland", "by": "Beelitz", "type": "urbanexploring", "beskrivelse": "Forlatt militærsykehus.", "tips": "Guidet tur.", "beste_tid": "april-oktober", "latitude": 52.2619, "longitude": 12.9197},
    {"navn": "Bamberg", "land": "Tyskland", "by": "Bamberg", "type": "gastronomi", "beskrivelse": "UNESCO-by med røykøl.", "tips": "Rauchbier på Schlenkerla.", "beste_tid": "hele året", "latitude": 49.8917, "longitude": 10.8917},
    {"navn": "Wünsdorf bunkerstadt", "land": "Tyskland", "by": "Wünsdorf", "type": "urbanexploring", "beskrivelse": "Forlatt sovjetisk militærby.", "tips": "Ta med kamera.", "beste_tid": "april-oktober", "latitude": 52.1931, "longitude": 13.4683},
    # ========== ØSTERRIKE ==========
    {"navn": "Café Central", "land": "Østerrike", "by": "Wien", "type": "kafé", "beskrivelse": "Trotskij, Freud og Lenin.", "tips": "Wiener Melange.", "beste_tid": "hele året", "latitude": 48.2103, "longitude": 16.3654},
    {"navn": "Hallstatt i regn", "land": "Østerrike", "by": "Hallstatt", "type": "kultur", "beskrivelse": "Magisk når turistene drar.", "tips": "Overnatt.", "beste_tid": "oktober-april", "latitude": 47.5622, "longitude": 13.6492},
    # ========== SLOVAKIA ==========
    {"navn": "Spišské Podhradie", "land": "Slovakia", "by": "Spišské Podhradie", "type": "kultur", "beskrivelse": "By under Europas største borg.", "tips": "Soloppgang på borgen.", "beste_tid": "mai-september", "latitude": 48.9994, "longitude": 20.7519},
    {"navn": "Martin", "land": "Slovakia", "by": "Martin", "type": "kultur", "beskrivelse": "Autentisk kulturhovedstad.", "tips": "Mala Fatra.", "beste_tid": "mai-september", "latitude": 49.0650, "longitude": 18.9219},
    {"navn": "Banská Bystrica", "land": "Slovakia", "by": "Banská Bystrica", "type": "kultur", "beskrivelse": "Historisk gruveby.", "tips": "SNP-museet.", "beste_tid": "mai-september", "latitude": 48.7389, "longitude": 19.1497},
    {"navn": "Čičmany", "land": "Slovakia", "by": "Čičmany", "type": "kultur", "beskrivelse": "Målte trehus.", "tips": "Bo i tradisjonelt hus.", "beste_tid": "mai-september", "latitude": 48.9556, "longitude": 18.5164},
    # ========== ROMANIA ==========
    {"navn": "Constanța", "land": "Romania", "by": "Constanța", "type": "kultur", "beskrivelse": "Havneby ved Svartehavet.", "tips": "Mosaikkmuseet.", "beste_tid": "mai-september", "latitude": 44.1792, "longitude": 28.6497},
    {"navn": "Băile Tușnad", "land": "Romania", "by": "Băile Tușnad", "type": "natur", "beskrivelse": "Vulkansk sjø.", "tips": "Bjørnesafari.", "beste_tid": "juni-september", "latitude": 46.1461, "longitude": 25.8603},
    {"navn": "Maramureș", "land": "Romania", "by": "Maramureș", "type": "kultur", "beskrivelse": "Hestekjerrer og trekirker.", "tips": "Besøk lokal familie.", "beste_tid": "mai-september", "latitude": 47.6581, "longitude": 24.0628},
    {"navn": "Sibiu", "land": "Romania", "by": "Sibiu", "type": "kultur", "beskrivelse": "Hus med øyne.", "tips": "Crama Sibiul Vechi.", "beste_tid": "mai-september", "latitude": 45.7983, "longitude": 24.1256},
    # ========== TSJEKKIA ==========
    {"navn": "Olomouc", "land": "Tsjekkia", "by": "Olomouc", "type": "kultur", "beskrivelse": "Vakkert som Praha – uten turister.", "tips": "Astronomisk klokke.", "beste_tid": "april-oktober", "latitude": 49.5939, "longitude": 17.2508},
    {"navn": "Český Krumlov i november", "land": "Tsjekkia", "by": "Český Krumlov", "type": "kultur", "beskrivelse": "Eventyrby i tåke.", "tips": "Bo på gammelt vertshus.", "beste_tid": "november", "latitude": 48.8128, "longitude": 14.3145},
    {"navn": "Kutná Hora", "land": "Tsjekkia", "by": "Kutná Hora", "type": "historie", "beskrivelse": "Benkirke med 40 000 skjeletter.", "tips": "Les historien.", "beste_tid": "hele året", "latitude": 49.9519, "longitude": 15.2678},
    # ========== UNGARN ==========
    {"navn": "New York Café", "land": "Ungarn", "by": "Budapest", "type": "kafé", "beskrivelse": "Verdens vakreste kafé.", "tips": "Bare en kaffe.", "beste_tid": "hele året", "latitude": 47.5025, "longitude": 19.0733},
    {"navn": "Pécs", "land": "Ungarn", "by": "Pécs", "type": "kultur", "beskrivelse": "Middelhavsstemning.", "tips": "Zsolnay-museet.", "beste_tid": "april-oktober", "latitude": 46.0728, "longitude": 18.2322},
    {"navn": "Egersalók", "land": "Ungarn", "by": "Egersalók", "type": "natur", "beskrivelse": "Pamukkale uten folk.", "tips": "Bad ved solnedgang.", "beste_tid": "hele året", "latitude": 47.8547, "longitude": 20.3325},
    # ========== POLEN ==========
    {"navn": "Krzywy Las", "land": "Polen", "by": "Gryfino", "type": "natur", "beskrivelse": "400 bøyde trær.", "tips": "Fotografer i tåke.", "beste_tid": "hele året", "latitude": 53.2139, "longitude": 14.4750},
    {"navn": "Wieliczka saltgruve", "land": "Polen", "by": "Wieliczka", "type": "eventyr", "beskrivelse": "Katedral i salt.", "tips": "Slikk veggen.", "beste_tid": "hele året", "latitude": 49.9831, "longitude": 20.0536},
    # ========== BALTIKUM ==========
    {"navn": "Korshøyden", "land": "Litauen", "by": "Šiauliai", "type": "kultur", "beskrivelse": "200 000 kors.", "tips": "Ta med eget kors.", "beste_tid": "hele året", "latitude": 56.0153, "longitude": 23.4164},
    {"navn": "Tartu", "land": "Estland", "by": "Tartu", "type": "kultur", "beskrivelse": "Ung universitetsby.", "tips": "Aparaaditehas.", "beste_tid": "mai-september", "latitude": 58.3780, "longitude": 26.7290},
    {"navn": "Kuldīga", "land": "Latvia", "by": "Kuldīga", "type": "natur", "beskrivelse": "Europas bredeste vannfall.", "tips": "Gå på elvebunnen.", "beste_tid": "mai-september", "latitude": 56.9678, "longitude": 21.9722},
    # ========== PORTUGAL ==========
    {"navn": "Monsaraz", "land": "Portugal", "by": "Monsaraz", "type": "kultur", "beskrivelse": "Hvitkalket landsby.", "tips": "Stjernekikking.", "beste_tid": "april-oktober", "latitude": 38.4436, "longitude": -7.3811},
    {"navn": "Café Majestic", "land": "Portugal", "by": "Porto", "type": "kafé", "beskrivelse": "Belle Époque fra 1921.", "tips": "Galão og pastel de nata.", "beste_tid": "hele året", "latitude": 41.1472, "longitude": -8.6067},
    {"navn": "Café A Brasileira", "land": "Portugal", "by": "Lisboa", "type": "kafé", "beskrivelse": "Pessoas stamkafé.", "tips": "Bica.", "beste_tid": "hele året", "latitude": 38.7106, "longitude": -9.1419},
    # ========== SPANIA ==========
    {"navn": "Castellfollit de la Roca", "land": "Spania", "by": "Castellfollit", "type": "natur", "beskrivelse": "By på 50 m basaltklippe.", "tips": "Foto nedenfra.", "beste_tid": "mars-november", "latitude": 42.2192, "longitude": 2.5539},
    {"navn": "Las Médulas", "land": "Spania", "by": "Las Médulas", "type": "natur", "beskrivelse": "Mars-lignende landskap.", "tips": "Gå i tunnelene.", "beste_tid": "april-oktober", "latitude": 42.4606, "longitude": -6.7686},
    # ========== ITALIA ==========
    {"navn": "Matera om natten", "land": "Italia", "by": "Matera", "type": "kultur", "beskrivelse": "Europas eldste by.", "tips": "Bo i grottehotell.", "beste_tid": "april-oktober", "latitude": 40.6667, "longitude": 16.6000},
    {"navn": "Civita di Bagnoregio", "land": "Italia", "by": "Civita", "type": "kultur", "beskrivelse": "Døende by på klippe.", "tips": "Gå over broen.", "beste_tid": "april-oktober", "latitude": 42.6278, "longitude": 12.1136},
    {"navn": "Craco", "land": "Italia", "by": "Craco", "type": "spøkstad", "beskrivelse": "Forlatt middelalderby.", "tips": "Guidet tur.", "beste_tid": "april-oktober", "latitude": 40.3789, "longitude": 16.4411},
    # ========== BALKAN ==========
    {"navn": "Mostar etter 17", "land": "Bosnia", "by": "Mostar", "type": "kultur", "beskrivelse": "Ekte Mostar.", "tips": "Burek ved elven.", "beste_tid": "mai-september", "latitude": 43.3433, "longitude": 17.8081},
    {"navn": "Kotor i januar", "land": "Montenegro", "by": "Kotor", "type": "natur", "beskrivelse": "Stille fjord.", "tips": "Båttur.", "beste_tid": "november-februar", "latitude": 42.4247, "longitude": 18.7712},
    {"navn": "Ohridsjøen", "land": "Nord-Makedonia", "by": "Ohrid", "type": "natur", "beskrivelse": "Europas eldste innsjø.", "tips": "Båt til St. Naum.", "beste_tid": "mai-september", "latitude": 41.1139, "longitude": 20.8028},
    {"navn": "Gjirokastër", "land": "Albania", "by": "Gjirokastër", "type": "kultur", "beskrivelse": "Steinby med herregårder.", "tips": "Bo i steinhus.", "beste_tid": "mai-september", "latitude": 40.0758, "longitude": 20.1389},
    {"navn": "Prizren", "land": "Kosovo", "by": "Prizren", "type": "kultur", "beskrivelse": "Osmansk perle.", "tips": "Kaffe ved elven.", "beste_tid": "mai-september", "latitude": 42.2139, "longitude": 20.7397},
    # ========== BULGARIA ==========
    {"navn": "Buzludzha", "land": "Bulgaria", "by": "Buzludzha", "type": "urbanexploring", "beskrivelse": "Forlatt UFO.", "tips": "Lommelykt.", "beste_tid": "juni-september", "latitude": 42.7358, "longitude": 25.3244},
    {"navn": "Rila-klosteret", "land": "Bulgaria", "by": "Rila", "type": "kultur", "beskrivelse": "Stripete arkitektur.", "tips": "Overnatt.", "beste_tid": "mai-september", "latitude": 42.1333, "longitude": 23.3403},
    {"navn": "Plovdivs gamleby", "land": "Bulgaria", "by": "Plovdiv", "type": "kultur", "beskrivelse": "Europas eldste by.", "tips": "Romersk teater.", "beste_tid": "april-oktober", "latitude": 42.1421, "longitude": 24.7508},
    # ========== FRANKRIKE ==========
    {"navn": "Les Machines de l'Île", "land": "Frankrike", "by": "Nantes", "type": "museum", "beskrivelse": "Mekaniske kjempedyr.", "tips": "Rid på elefanten.", "beste_tid": "hele året", "latitude": 47.2064, "longitude": -1.5642},
    {"navn": "Rochefort-en-Terre", "land": "Frankrike", "by": "Rochefort-en-Terre", "type": "kultur", "beskrivelse": "Vakreste landsby.", "tips": "Blomstersesong.", "beste_tid": "mai-september", "latitude": 47.6997, "longitude": -2.3367},
    # ========== BENELUX ==========
    {"navn": "Durbuy", "land": "Belgia", "by": "Durbuy", "type": "kultur", "beskrivelse": "Verdens minste by.", "tips": "Belgisk sjokolade.", "beste_tid": "mai-september", "latitude": 50.3522, "longitude": 5.4561},
    {"navn": "Groningen", "land": "Nederland", "by": "Groningen", "type": "kultur", "beskrivelse": "Sykkelby.", "tips": "Lei sykkel.", "beste_tid": "april-oktober", "latitude": 53.2194, "longitude": 6.5665},
    # ========== STORBRITANNIA/IRLAND ==========
    {"navn": "Skellig Michael", "land": "Irland", "by": "Skellig", "type": "historie", "beskrivelse": "Øy-kloster 500-tallet.", "tips": "Book tidlig.", "beste_tid": "mai-september", "latitude": 51.7719, "longitude": -10.5392},
    {"navn": "Portmeirion", "land": "Storbritannia", "by": "Portmeirion", "type": "kultur", "beskrivelse": "Italiensk drømmelandsby.", "tips": "Bo i landsbyen.", "beste_tid": "mai-september", "latitude": 52.9133, "longitude": -4.0994},
    {"navn": "Paldiski","by": "Paldiski","land": "Estland","type": "eventyr","latitude": 59.3512,"longitude": 24.0531,"beskrivelse": "En tidligere topphemmelig, lukket sovjetisk militærby på en vakker halvøy. Her lå det største treningssenteret for kjernefysiske ubåter i hele Sovjetunionen, og vanlige folk fikk ikke engang reise inn hit uten spesialtillatelse før i 1994. I dag er det et fascinerende, rått og spøkelsesaktig sted med forlatte kaserner, spektakulære kalksteinsklipper og et vakkert, rødt fyrtårn.","tips": "Klatre opp i fyrtårnet på Pakri-odden for en vill utsikt over Finskebukta.","pris": "€"},
    {"navn": "Deventer","by": "Deventer","land": "Nederland","type": "kultur","latitude": 52.2561,"longitude": 6.1604,"beskrivelse": "Glem overfylte Amsterdam! Deventer er en av de aller eldste byene i Nederland, vakkert plassert langs elven IJssel. Byen har en perfekt bevart middelalderkjerne med trange, svingete smug, urgamle mursteinshus og en herlig, tilbakelent atmosfære fri for turisthorder.","tips": "Smak på den tradisjonelle honningkaken 'Deventer Koek' på det historiske torget Brink.","pris": "€€"},
    {"navn": "Pitigliano","by": "Pitigliano","land": "Italia","type": "kultur","latitude": 42.6344,
    "longitude": 11.6675,"beskrivelse": "Ofte kalt 'Lille Jerusalem'. Dette er en spektakulær by i Toscana som er hugget direkte ut av en enorm klippe av vulkansk tuffstein. Husene ser ut som de vokser organisk opp fra fjellet. Byen er omringet av 'Vie Cave' – mystiske, dype og eldgamle veier som etruskerne hugget dypt ned i fjellet for over 2000 år siden.","tips": "Gå en tur i de svale etruskiske huleveiene (Vie Cave) som ligger like utenfor byporten.","pris": "€€"},
    {"navn": "Sala Silvergruva","by": "Sala","land": "Sverige","type": "eventyr","latitude": 59.9075,"longitude": 16.5702,
    "beskrivelse": "En av verdens best bevarte gruvemiljøer. I over 500 år var dette en av Sveriges viktigste sølvgruver. Det mest helsprø her er at de har bygget en hotellsuite – 'Gruvsviten' – hele 155 meter under bakken! Her sover du i et oppvarmet rom omringet av mørke, underjordiske sjakter og opplyste, mystiske gruvesjøer.","tips": "Ta med varme klær; det er rundt 2 plussgrader i gruvegangene, selv om hotellrommet heldigvis er godt oppvarmet.","pris": "€€€"},
    {"navn": "Bergen (Germany)", "by": "Bergen (Germany)", "land": "Tyskland", "type": "kultur", "latitude": 52.8103, "longitude": 9.9611, "beskrivelse": "En fantastisk destinasjon oppdaget via Wikivoyage.", "tips": "Sjekk Wikivoyage for lokale detaljer.", "pris": "€"},
    {"navn": "Orford Ness", "by": "Orford Ness", "land": "Storbritannia", "type": "kultur", "latitude": 52.0814, "longitude": 1.5586, "beskrivelse": "Fantastisk historisk sted kjent fra TV.", "tips": "Kjent fra TV-dokumentarer om sære og forlatte steder.", "pris": "€"},
    {"navn": "Imber", "by": "Imber", "land": "Storbritannia", "type": "kultur", "latitude": 51.234, "longitude": -2.051, "beskrivelse": "Fantastisk historisk sted kjent fra TV.", "tips": "Kjent fra TV-dokumentarer om sære og forlatte steder.", "pris": "€"},
    {"navn": "Tyneham", "by": "Tyneham", "land": "Storbritannia", "type": "kultur", "latitude": 50.623, "longitude": -2.169, "beskrivelse": "Fantastisk historisk sted kjent fra TV.", "tips": "Kjent fra TV-dokumentarer om sære og forlatte steder.", "pris": "€"},
    {"navn": "Stroma", "by": "Stroma", "land": "Storbritannia", "type": "kultur", "latitude": 58.68, "longitude": -3.12, "beskrivelse": "Fantastisk historisk sted kjent fra TV.", "tips": "Kjent fra TV-dokumentarer om sære og forlatte steder.", "pris": "€"},
    {"navn": "Scapa Flow", "by": "Scapa Flow", "land": "Storbritannia", "type": "kultur", "latitude": 58.9, "longitude": -3.05, "beskrivelse": "Fantastisk historisk sted kjent fra TV.", "tips": "Kjent fra TV-dokumentarer om sære og forlatte steder.", "pris": "€"},
    {"navn": "Prora", "by": "Prora", "land": "Tyskland", "type": "kultur", "latitude": 54.4389, "longitude": 13.575, "beskrivelse": "Fantastisk historisk sted kjent fra TV.", "tips": "Kjent fra TV-dokumentarer om sære og forlatte steder.", "pris": "€"},
    {"navn": "Teufelsberg", "by": "Teufelsberg", "land": "Tyskland", "type": "kultur", "latitude": 52.4977, "longitude": 13.2429, "beskrivelse": "Fantastisk historisk sted kjent fra TV.", "tips": "Kjent fra TV-dokumentarer om sære og forlatte steder.", "pris": "€"},
    {"navn": "Kelvedon Hatch Secret Nuclear Bunker", "by": "Kelvedon Hatch Secret Nuclear Bunker", "land": "Storbritannia", "type": "kultur", "latitude": 51.6718, "longitude": 0.2566, "beskrivelse": "Fantastisk historisk sted kjent fra TV.", "tips": "Kjent fra TV-dokumentarer om sære og forlatte steder.", "pris": "€"},
    {"navn": "Dunmore Pineapple", "by": "Dunmore Pineapple", "land": "Storbritannia", "type": "kultur", "latitude": 56.0767, "longitude": -3.7867, "beskrivelse": "Fantastisk historisk sted kjent fra TV.", "tips": "Kjent fra TV-dokumentarer om sære og forlatte steder.", "pris": "€"},
    {"navn": "Heeresversuchsanstalt Peenemünde", "by": "Heeresversuchsanstalt Peenemünde", "land": "Tyskland", "type": "kultur", "latitude": 54.1482, "longitude": 13.794, "beskrivelse": "Fantastisk historisk sted kjent fra TV.", "tips": "Kjent fra TV-dokumentarer om sære og forlatte steder.", "pris": "€"},
    {"navn": "Wieliczka Salt Mine", "by": "Wieliczka Salt Mine", "land": "Polen", "type": "kultur", "latitude": 49.9792, "longitude": 20.0639, "beskrivelse": "Fantastisk historisk sted kjent fra TV.", "tips": "Kjent fra TV-dokumentarer om sære og forlatte steder.", "pris": "€"},
    {"navn": "Pluckley", "by": "Pluckley", "land": "Storbritannia", "type": "kultur", "latitude": 51.1761, "longitude": 0.7578, "beskrivelse": "Fantastisk historisk sted kjent fra TV.", "tips": "Kjent fra TV-dokumentarer om sære og forlatte steder.", "pris": "€"},
    {"navn": "Waldspirale", "by": "Waldspirale", "land": "Tyskland", "type": "kultur", "latitude": 49.8856, "longitude": 8.6558, "beskrivelse": "Fantastisk historisk sted kjent fra TV.", "tips": "Kjent fra TV-dokumentarer om sære og forlatte steder.", "pris": "€"},
    {"navn": "Reschensee", "by": "Reschensee", "land": "Italia", "type": "kultur", "latitude": 46.801, "longitude": 10.531, "beskrivelse": "Fantastisk historisk sted kjent fra TV.", "tips": "Kjent fra TV-dokumentarer om sære og forlatte steder.", "pris": "€"},
    # ========== TV-STEDER (manuelt lagt til fra hent_tv_steder.py) ==========
    {"navn": "Maunsell Forts", "by": "Maunsell Forts", "land": "Storbritannia", "type": "kultur", "latitude": 51.4667, "longitude": 1.1000, "beskrivelse": "Forlatte flåtefort fra andre verdenskrig i Nordsjøen, bygget for å forsvare London mot tyske fly.", "tips": "Båtutflukt fra Whitstable eller Southend-on-Sea.", "pris": "€"},
    {"navn": "Bannerman's Castle", "by": "Bannerman's Castle", "land": "Storbritannia", "type": "kultur", "latitude": 41.4556, "longitude": -73.9875, "beskrivelse": "Forlatt våpenlager bygget som et skotsk slott på en øy i Hudson-elven.", "tips": "Ta fergen fra Beacon, New York.", "pris": "€"},
    {"navn": "The Forbidden Corner", "by": "The Forbidden Corner", "land": "Storbritannia", "type": "kultur", "latitude": 54.2800, "longitude": -1.8800, "beskrivelse": "En særegen labyrint av tunneler, hager og skjulte rom i Yorkshire Dales.", "tips": "Book billett på forhånd – det er ofte utsolgt.", "pris": "€€"},
    {"navn": "Spreepark", "by": "Spreepark", "land": "Tyskland", "type": "kultur", "latitude": 52.4875, "longitude": 13.4611, "beskrivelse": "Forlatt fornøyelsespark i Berlin, stengt siden 2002, med rustne karuseller og overgrodd natur.", "tips": "Guidet tur er eneste måte å komme inn på.", "pris": "€"},
    {"navn": "Regierungsbunker", "by": "Regierungsbunker", "land": "Tyskland", "type": "kultur", "latitude": 50.5833, "longitude": 7.2167, "beskrivelse": "Hemmelig tysk regjeringsbunker fra den kalde krigen, bygget for å huse regjeringen i tilfelle atomkrig.", "tips": "Museum i Ahrweiler – guidet tur anbefales.", "pris": "€"},
    {"navn": "Sankt Nikolai, Hamburg", "by": "Sankt Nikolai, Hamburg", "land": "Tyskland", "type": "kultur", "latitude": 53.5475, "longitude": 9.9900, "beskrivelse": "Ruinen av en nygotisk kirke, bombet under andre verdenskrig, nå et minnesmerke mot krig.", "tips": "Ta heisen opp i tårnet for panoramautsikt over Hamburg.", "pris": "€"},
    {"navn": "Vogelsang Ordensburg", "by": "Vogelsang Ordensburg", "land": "Tyskland", "type": "kultur", "latitude": 50.5833, "longitude": 6.4500, "beskrivelse": "Tidligere nazistisk ordensborg i Eifel, senere brukt av britene og belgierne som militærbase.", "tips": "Utstillingen 'Bestimmung: Herrenmensch' er svært grundig.", "pris": "€"},
    {"navn": "Project Riese", "by": "Project Riese", "land": "Polen", "type": "kultur", "latitude": 50.6833, "longitude": 16.4167, "beskrivelse": "Et enormt, uferdig nazistisk tunnelkompleks i Uglefjellene, bygget av tvangsarbeidere.", "tips": "Ta med lommelykt og gode sko – tunnelene er mørke og ujevne.", "pris": "€"},
    {"navn": "Kaplica Czaszek", "by": "Kaplica Czaszek", "land": "Polen", "type": "kultur", "latitude": 50.5833, "longitude": 16.3333, "beskrivelse": "En skjelettkirke dekorert med hodeskaller og bein fra over 3000 mennesker.", "tips": "Kombiner med en tur til den nærliggende festningen i Kłodzko.", "pris": "€"},
    {"navn": "Wilcze Gardło", "by": "Wilcze Gardło", "land": "Polen", "type": "kultur", "latitude": 54.0000, "longitude": 21.1333, "beskrivelse": "Tysk ulvehule fra andre verdenskrig, skjult i skogene i Masuria.", "tips": "Guidet tur gir best innsikt i historien.", "pris": "€"},
    {"navn": "Palais Idéal", "by": "Palais Idéal", "land": "Frankrike", "type": "kultur", "latitude": 45.2667, "longitude": 4.7500, "beskrivelse": "Et eventyrlig, naivistisk palass bygget for hånd av postbudet Ferdinand Cheval over 33 år.", "tips": "Kom tidlig for å unngå kø – det er populært.", "pris": "€"},
    # ========== ROSTIGA ROADTRIPS: SESONG 1 & 2 ==========
    {"navn": "Bilkirkegården i Båstnäs (Rostiga Roadtrips)", "land": "Sverige", "by": "Töcksfors", "type": "kultur", "latitude": 59.3615, "longitude": 11.8422, "beskrivelse": "Bilkirkegård fra Rostiga Roadtrips.", "tips": "Utforsk de rustne veteranbilene.", "pris": "€"},
    {"navn": "Nordstrandischmoor (Traktortog på havbunnen - Rostiga Roadtrips)", "land": "Tyskland", "by": "Nordstrand", "type": "kultur", "latitude": 54.5502, "longitude": 8.8118, "beskrivelse": "Traktortog over havbunnen fra Rostiga Roadtrips.", "tips": "Ta turen ut til halligene.", "pris": "€"},
    {"navn": "Automuseum Melle (Levende veteranbiler - Rostiga Roadtrips)", "land": "Tyskland", "by": "Melle", "type": "kultur", "latitude": 52.2031, "longitude": 8.3414, "beskrivelse": "Levende veteranbilmuseum fra Rostiga Roadtrips.", "tips": "Se de gamle bilene i aksjon.", "pris": "€"},
    {"navn": "Worpswede (Ekspresjonistisk Kunstnerkoloni - Rostiga Roadtrips)", "land": "Tyskland", "by": "Worpswede", "type": "kultur", "latitude": 53.2217, "longitude": 8.9267, "beskrivelse": "Ekspresjonistisk kunstnerkoloni fra Rostiga Roadtrips.", "tips": "Besøk Barkenhoff-museet.", "pris": "€"},
    {"navn": "Mumienkeller Bleicherode (Mumiehvelvet - Rostiga Roadtrips)", "land": "Tyskland", "by": "Bleicherode", "type": "kultur", "latitude": 51.4402, "longitude": 10.5714, "beskrivelse": "Mumiehvelv fra Rostiga Roadtrips.", "tips": "Se de naturlige mumiene.", "pris": "€"},
    {"navn": "Doruchów (Heksebrenningsmonumentet - Rostiga Roadtrips)", "land": "Polen", "by": "Doruchów", "type": "kultur", "latitude": 51.4172, "longitude": 18.0694, "beskrivelse": "Heksebrenningsmonument fra Rostiga Roadtrips.", "tips": "Historisk minnesmerke.", "pris": "€"},
    {"navn": "Łódź (Sveriges Hollywood & Mystikk - Rostiga Roadtrips)", "land": "Polen", "by": "Łódź", "type": "kultur", "latitude": 51.7592, "longitude": 19.4560, "beskrivelse": "Polsk filmby fra Rostiga Roadtrips.", "tips": "Gå langs Piotrkowska-gaten.", "pris": "€"},
    {"navn": "Bolwoningen (Kulehusene i Den Bosch - Rostiga Roadtrips)", "land": "Nederland", "by": "'s-Hertogenbosch", "type": "kultur", "latitude": 51.7183, "longitude": 5.3377, "beskrivelse": "Kulehus fra Rostiga Roadtrips.", "tips": "Unik arkitektur.", "pris": "€"},
    {"navn": "CasAnus (Tarmhotellet i Kemzeke - Rostiga Roadtrips)", "land": "Belgia", "by": "Kemzeke", "type": "kultur", "latitude": 51.2075, "longitude": 4.0674, "beskrivelse": "Tarmhotell fra Rostiga Roadtrips.", "tips": "Overnatt i den unike konstruksjonen.", "pris": "€"},
    {"navn": "Triumfbue-rundkjøringen (Rondellkaos - Rostiga Roadtrips)", "land": "Frankrike", "by": "Paris", "type": "kultur", "latitude": 48.8738, "longitude": 2.2950, "beskrivelse": "Rundkjøringen rundt Triumfbuen fra Rostiga Roadtrips.", "tips": "Ta metroen i stedet.", "pris": "€"},
    {"navn": "Iron Bridge (Verdens første jernbro - Rostiga Roadtrips)", "land": "Storbritannia", "by": "Ironbridge", "type": "kultur", "latitude": 52.6272, "longitude": -2.4855, "beskrivelse": "Verdens første jernbro fra Rostiga Roadtrips.", "tips": "Besøk broens museum.", "pris": "€"},
    {"navn": "Blowing Stone (Viking-fløytestenen - Rostiga Roadtrips)", "land": "Storbritannia", "by": "Shrivenham", "type": "kultur", "latitude": 51.5714, "longitude": -1.5684, "beskrivelse": "Viking-fløytestenen fra Rostiga Roadtrips.", "tips": "Prøv å blåse i steinen.", "pris": "€"},
    {"navn": "Lea & Perrins (Sausfabrikken i Worcester - Rostiga Roadtrips)", "land": "Storbritannia", "by": "Worcester", "type": "kultur", "latitude": 52.1936, "longitude": -2.2144, "beskrivelse": "Worcestersausfabrikken fra Rostiga Roadtrips.", "tips": "Smak på original Worcestersaus.", "pris": "€"},
    {"navn": "Whitstable (Ostronhuvudstad & Skalldyr - Rostiga Roadtrips)", "land": "Storbritannia", "by": "Whitstable", "type": "kultur", "latitude": 51.3607, "longitude": 1.0257, "beskrivelse": "Ostronhovedstad fra Rostiga Roadtrips.", "tips": "Spis ferske østers ved havnen.", "pris": "€€"},
    {"navn": "Isle of Man (Peel P50 Mikrobiler - Rostiga Roadtrips)", "land": "Storbritannia", "by": "Peel", "type": "kultur", "latitude": 54.2219, "longitude": -4.6908, "beskrivelse": "Peel P50 mikrobiler fra Rostiga Roadtrips.", "tips": "Besøk bilmuseet på øya.", "pris": "€"},
    {"navn": "Valencia (Det spanske nasjonalmålet - Rostiga Roadtrips)", "land": "Spania", "by": "Valencia", "type": "kultur", "latitude": 39.4699, "longitude": -0.3763, "beskrivelse": "Spansk nasjonalmål fra Rostiga Roadtrips.", "tips": "Prøv paella i Valencia.", "pris": "€€"},
    # ========== HÅNDPLUKKEDE SKJULTE PERLER: ITALIA ==========
    {"navn": "Calcata Vecchia", "land": "Italia", "by": "Calcata", "type": "kunstnerlandsby", "beskrivelse": "En dramatisk middelalderlandsby på en tuffklippe nord for Roma, reddet av kunstnere, håndverkere og bohemer etter at den nesten ble fraflyttet.", "tips": "Kom på en ukedag og gå innom de små atelierene før solnedgang over Treja-dalen.", "beste_tid": "mars-juni, september-november", "latitude": 42.2195, "longitude": 12.4257, "pris": "€€"},
    {"navn": "Dozza", "land": "Italia", "by": "Dozza", "type": "gatekunst", "beskrivelse": "En liten befestet landsby i Emilia-Romagna der husveggene er dekket av store kunstverk og hele sentrum fungerer som et åpent galleri.", "tips": "Kombiner muralvandring med vinsmaking i Enoteca Regionale under borgen.", "beste_tid": "april-oktober", "latitude": 44.3608, "longitude": 11.6286, "pris": "€€"},
    {"navn": "Santo Stefano di Sessanio", "land": "Italia", "by": "Santo Stefano di Sessanio", "type": "fjellandsby", "beskrivelse": "En nesten forlatt steinlandsby høyt i Abruzzo, langsomt restaurert til et atmosfærisk albergo diffuso omgitt av fjell og sauebeiter.", "tips": "Bo i et restaurert steinhus og kjør videre til Campo Imperatore ved daggry.", "beste_tid": "mai-oktober", "latitude": 42.3436, "longitude": 13.6447, "pris": "€€"},
    {"navn": "Bussana Vecchia", "land": "Italia", "by": "Sanremo", "type": "kunstnerkoloni", "beskrivelse": "En jordskjelvødelagt ligurisk landsby som ble tatt tilbake av kunstnere på 1960-tallet, med ruiner, gallerier og frodige smug.", "tips": "Gå hit tidlig fra Bussana Nuova og spis lunsj i en av de skjulte gårdsrommene.", "beste_tid": "mars-juni, september-oktober", "latitude": 43.8371, "longitude": 7.8280, "pris": "€€"},
    {"navn": "Vitorchiano", "land": "Italia", "by": "Vitorchiano", "type": "middelalderby", "beskrivelse": "En kompakt steinby i Lazio bygget på vulkansk klippe, med smale passasjer, hengende hager og en uventet Moai-statue.", "tips": "Følg stien ned under bymuren for det beste perspektivet på klippebyen.", "beste_tid": "april-juni, september-november", "latitude": 42.4655, "longitude": 12.1712, "pris": "€"},
    # ========== HÅNDPLUKKEDE SKJULTE PERLER: SPANIA ==========
    {"navn": "Albarracín", "land": "Spania", "by": "Albarracín", "type": "middelalderby", "beskrivelse": "Rosa-rød fjellby i Aragón med skjeve hus, bymurer og labyrintiske smug som føles som en filmkulisse uten kystturismen.", "tips": "Gå bymurene rett før solnedgang og overnatt for å få byen nesten alene.", "beste_tid": "april-juni, september-oktober", "latitude": 40.4083, "longitude": -1.4430, "pris": "€€"},
    {"navn": "Mallos de Riglos", "land": "Spania", "by": "Riglos", "type": "natur", "beskrivelse": "En liten landsby presset inn under enorme røde konglomeratklipper, kjent blant klatrere men ofte oversett av vanlige reisende.", "tips": "Ta rundløypa Camino del Cielo for utsikt mot gribber, klipper og landsbyen.", "beste_tid": "mars-juni, september-november", "latitude": 42.3486, "longitude": -0.7278, "pris": "€"},
    {"navn": "Frías", "land": "Spania", "by": "Frías", "type": "historie", "beskrivelse": "En av Spanias minste byer, balansert på en kalksteinsrygg med hengende hus, borg og en middelalderbro over Ebro.", "tips": "Kombiner med Tobera-fossene og kom om morgenen før dagsbesøkende.", "beste_tid": "april-oktober", "latitude": 42.7625, "longitude": -3.2933, "pris": "€"},
    {"navn": "Bardenas Reales", "land": "Spania", "by": "Arguedas", "type": "ørkenlandskap", "beskrivelse": "Et halvtørt månelandskap i Navarra med leirformasjoner, raviner og støvete veier som føles mer Arizona enn Nord-Spania.", "tips": "Kjør ruten rundt Castildetierra tidlig eller sent for dramatisk lys og mindre varme.", "beste_tid": "mars-juni, september-november", "latitude": 42.1889, "longitude": -1.5150, "pris": "€"},
    {"navn": "Ujué", "land": "Spania", "by": "Ujué", "type": "pilegrimsby", "beskrivelse": "En liten navarrisk åsby med festningskirke, steinhus og vid utsikt mot Pyreneene og vinmarkene.", "tips": "Prøv migas eller mandelkaker etter besøket i Santa María de Ujué.", "beste_tid": "april-juni, september-oktober", "latitude": 42.5058, "longitude": -1.4992, "pris": "€"},
    # ========== HÅNDPLUKKEDE SKJULTE PERLER: FRANKRIKE ==========
    {"navn": "Conques", "land": "Frankrike", "by": "Conques-en-Rouergue", "type": "pilegrimsby", "beskrivelse": "En kompakt middelalderlandsby i Aveyron med romansk klosterkirke, brosteinsgater og gyllent kveldslys over skifertak.", "tips": "Bli til etter at pilegrimene har gått videre og se Soulages-vinduene i kirken.", "beste_tid": "april-juni, september-oktober", "latitude": 44.5990, "longitude": 2.3971, "pris": "€€"},
    {"navn": "La Couvertoirade", "land": "Frankrike", "by": "La Couvertoirade", "type": "tempelridderlandsby", "beskrivelse": "En befestet landsby på Larzac-platået, knyttet til tempelriddere og hospitalriddere, med intakte murer og vindpisket steinlandskap.", "tips": "Gå utenfor murene for å se byen ligge som en steinfestning i det åpne landskapet.", "beste_tid": "mai-oktober", "latitude": 43.9130, "longitude": 3.3169, "pris": "€"},
    {"navn": "Moustiers-Sainte-Marie", "land": "Frankrike", "by": "Moustiers-Sainte-Marie", "type": "fjellandsby", "beskrivelse": "En provençalsk landsby under kalksteinsklipper, kjent for keramikk og en gullstjerne som henger i lenke mellom fjellveggene.", "tips": "Gå opp til kapellet Notre-Dame de Beauvoir før lunsj og fortsett til Verdon-juvet.", "beste_tid": "april-juni, september-oktober", "latitude": 43.8467, "longitude": 6.2215, "pris": "€€"},
    {"navn": "Saint-Cirq-Lapopie", "land": "Frankrike", "by": "Saint-Cirq-Lapopie", "type": "kunstnerlandsby", "beskrivelse": "En dramatisk landsby høyt over Lot-elven, elsket av surrealister og full av steinhus, trapper og utsiktspunkter.", "tips": "Gå slepestien Chemin de Halage langs elven for en roligere opplevelse.", "beste_tid": "april-juni, september-oktober", "latitude": 44.4658, "longitude": 1.6706, "pris": "€€"},
    {"navn": "Salins-les-Bains", "land": "Frankrike", "by": "Salins-les-Bains", "type": "industrihistorie", "beskrivelse": "En undervurdert kur- og saltby i Jura med underjordiske saltgallerier, termalbad og bratte kalksteinsfort rundt dalen.", "tips": "Besøk Grande Saline og ta deretter kabelbanen eller stien opp til Fort Saint-André.", "beste_tid": "mai-oktober", "latitude": 46.9406, "longitude": 5.8778, "pris": "€€"},
    # ========== HÅNDPLUKKEDE SKJULTE PERLER: TYSKLAND ==========
    {"navn": "Monschau", "land": "Tyskland", "by": "Monschau", "type": "bindingsverksby", "beskrivelse": "En trang dalby i Eifel med mørke bindingsverkshus, brosteinsgater og sennepsmølle, langt roligere enn de store romantiske rutene.", "tips": "Gå opp til utsiktspunktet over Rotes Haus før du besøker sennepsmøllen.", "beste_tid": "april-juni, september-desember", "latitude": 50.5545, "longitude": 6.2400, "pris": "€€"},
    {"navn": "Lüneburg", "land": "Tyskland", "by": "Lüneburg", "type": "hanseatisk kultur", "beskrivelse": "En tidligere saltby med skjeve mursteinsfasader, smug og havnekanter som gir ekte nordtysk atmosfære uten Hamburg-tempoet.", "tips": "Se de skjeve husene i Senkungsgebiet og avslutt ved Stintmarkt.", "beste_tid": "april-oktober", "latitude": 53.2464, "longitude": 10.4115, "pris": "€€"},
    {"navn": "Bastei ved soloppgang", "land": "Tyskland", "by": "Rathen", "type": "natur", "beskrivelse": "Sandsteinstårn og broer i Sächsische Schweiz, spektakulært kjent lokalt men fortsatt magisk hvis du kommer før turistbussene.", "tips": "Overnatt i Rathen og gå opp før frokost for tåke over Elben.", "beste_tid": "april-juni, september-oktober", "latitude": 50.9669, "longitude": 14.0656, "pris": "€"},
    {"navn": "Quedlinburg bakgatene", "land": "Tyskland", "by": "Quedlinburg", "type": "unesco", "beskrivelse": "UNESCO-by med over tusen bindingsverkshus, men de beste opplevelsene ligger i de stille smugene vekk fra markedsplassen.", "tips": "Gå til Münzenberg-kvartalet for små hus, utsikt og færre folk.", "beste_tid": "april-oktober, desember", "latitude": 51.7884, "longitude": 11.1416, "pris": "€€"},
    {"navn": "Völklinger Hütte", "land": "Tyskland", "by": "Völklingen", "type": "industriarv", "beskrivelse": "Et enormt nedlagt jernverk i Saarland, nå UNESCO-sted med gangbroer, rust, kunstutstillinger og nesten sci-fi-aktig industriarkitektur.", "tips": "Sett av minst tre timer og gå opp på de høye plattformene for full effekt.", "beste_tid": "hele året", "latitude": 49.2494, "longitude": 6.8442, "pris": "€€"},
    # ========== HÅNDPLUKKEDE SKJULTE PERLER: POLEN ==========
    {"navn": "Zalipie", "land": "Polen", "by": "Zalipie", "type": "folkekunst", "beskrivelse": "En landsby der hus, brønner og fjøs er dekorert med håndmalte blomster, en levende folkekunsttradisjon langt fra storbyrutene.", "tips": "Start ved Dom Malarek og gå videre mellom gårdene til fots eller på sykkel.", "beste_tid": "mai-september", "latitude": 50.2356, "longitude": 20.8622, "pris": "€"},
    {"navn": "Srebrna Góra festning", "land": "Polen", "by": "Srebrna Góra", "type": "festning", "beskrivelse": "En massiv prøyssisk fjellfestning i Nedre Schlesien, bygget som et militært monster over skogkledde åser.", "tips": "Ta guidet tur i kasemattene og kombiner med utsikten fra Donjon.", "beste_tid": "april-oktober", "latitude": 50.5700, "longitude": 16.6425, "pris": "€"},
    {"navn": "Książ slottets tunneler", "land": "Polen", "by": "Wałbrzych", "type": "mysterie", "beskrivelse": "Et eventyrslott over en ravine med et mørkere lag under bakken, knyttet til nazistenes uferdige Project Riese.", "tips": "Velg billett som inkluderer underjordisk rute, ikke bare slottsrommene.", "beste_tid": "hele året", "latitude": 50.8422, "longitude": 16.2920, "pris": "€€"},
    {"navn": "Tykocin", "land": "Polen", "by": "Tykocin", "type": "jødisk historie", "beskrivelse": "En liten Podlasie-by med barokk torg, bevart synagoge og tung, viktig historie i et landskap få turister prioriterer.", "tips": "Besøk synagogen og spis regional mat før du drar videre mot Biebrza-myrene.", "beste_tid": "mai-september", "latitude": 53.2056, "longitude": 22.7742, "pris": "€"},
    {"navn": "Błędówørkenen", "land": "Polen", "by": "Klucze", "type": "ørkenlandskap", "beskrivelse": "Europas merkeligste innlandsørkenfølelse: sandflater og furuskog i Schlesien, en surreal kontrast til regionens industribyer.", "tips": "Start ved utsiktspunktet Czubatka og kom i gyllent kveldslys.", "beste_tid": "april-oktober", "latitude": 50.3361, "longitude": 19.5567, "pris": "€"},
]

# ========================================
# SPANIA – kuratert markedspakke for nordmenn (Costa Blanca, Andalucía m.m.)
# type = profilinteresse; normaliseres til DB-kategori i data_store
# ========================================
SPANIA_MARKEDSDATA = [
    {
        "id": "es_gem_01",
        "navn": "Setenil de las Bodegas",
        "by": "Ronda/Cádiz",
        "land": "Spania",
        "country_code": "ES",
        "type": "Kultur & Historie",
        "latitude": 36.8639,
        "longitude": -5.1812,
        "beskrivelse": "En helt unik hvit landsby hvor husene er bygget direkte inn under massive overhengende klipper. Fjellet fungerer som naturlig beskyttelse mot solen.",
        "tips": "Gå ned i gaten 'Cuevas del Sol' for å sitte under fjellet.",
        "beste_tid": "Vår og høst.",
        "pris": "€",
    },
    {
        "id": "es_gem_02",
        "navn": "El Castell de Guadalest",
        "by": "Alicante (Baklandet)",
        "land": "Spania",
        "country_code": "ES",
        "type": "Natur & Aktivitet",
        "latitude": 38.6772,
        "longitude": -0.1981,
        "beskrivelse": "En dramatisk festningslandsby tilgjengelig via en uthugget tunnel i fjellet, med utsikt over en smaragdgrønn innsjø.",
        "tips": "Perfekt dagsutflukt fra Costa Blanca. Kom tidlig.",
        "beste_tid": "September til mai.",
        "pris": "€",
    },
    {
        "id": "es_gem_03",
        "navn": "Las Colinas Oasis",
        "by": "Orihuela Costa",
        "land": "Spania",
        "country_code": "ES",
        "type": "Golf",
        "latitude": 37.9314,
        "longitude": -0.7915,
        "beskrivelse": "En prisbelønnet mesterskapsbane som ligger skjult i en dyp dal omgitt av sitronlunder unna kystens mas.",
        "tips": "Klubbhuset og restauranten er verdt et besøk selv om du ikke spiller.",
        "beste_tid": "Oktober til mai.",
        "pris": "€€",
    },
    {
        "id": "es_gem_04",
        "navn": "Altea gamleby",
        "by": "Altea",
        "land": "Spania",
        "country_code": "ES",
        "type": "Kultur & Historie",
        "latitude": 38.5992,
        "longitude": -0.0519,
        "beskrivelse": "Hvitkalkede gater, blå kuppeltak og kunstneratelierer på en ås over Costa Blanca – roligere enn Benidorm, men like lett tilgjengelig for nordmenn.",
        "tips": "Gå opp til Iglesia de Nuestra Señora del Consuelo ved solnedgang.",
        "beste_tid": "April til juni og september til november.",
        "pris": "€",
    },
    {
        "id": "es_rest_01",
        "navn": "Venta El Túnel",
        "by": "Málaga",
        "land": "Spania",
        "country_code": "ES",
        "type": "Mat & Vin",
        "latitude": 36.7812,
        "longitude": -4.4214,
        "beskrivelse": "Legendarisk venta i Montes de Málaga siden 1953 – kjent for caldoso-arroz, migas og serrano-retter i skogrike omgivelser, langt fra kystens køer.",
        "tips": "Bestill på forhånd i helgene og prøv arroz con pollo caldoso.",
        "beste_tid": "Hele året.",
        "pris": "€€",
    },
]

LOKALE_SPISESTEDER = [
    {"navn": "Feskekôrka", "land": "Sverige", "by": "Göteborg", "type": "sjømat", "beskrivelse": "Torghall for fisk.", "pris": "100-200 SEK", "latitude": 57.7014, "longitude": 11.9578},
    {"navn": "Pelikan", "land": "Sverige", "by": "Stockholm", "type": "husmannskost", "beskrivelse": "Husmannskost siden 1664.", "pris": "150-250 SEK", "latitude": 59.3108, "longitude": 18.0792},
    {"navn": "Lilla Ego", "land": "Sverige", "by": "Stockholm", "type": "nordisk", "beskrivelse": "Hemmelig restaurant.", "pris": "200-400 SEK", "latitude": 59.3444, "longitude": 18.0469},
    {"navn": "Bakfickan", "land": "Sverige", "by": "Stockholm", "type": "husmannskost", "beskrivelse": "Operakjellerens bakside.", "pris": "150-300 SEK", "latitude": 59.3303, "longitude": 18.0703},
    {"navn": "Kaffestuggu", "land": "Norge", "by": "Røros", "type": "kafé", "beskrivelse": "Rømmegrøt i historisk miljø.", "pris": "100-200 NOK", "latitude": 62.5746, "longitude": 11.3853},
    {"navn": "Schønnemann", "land": "Danmark", "by": "København", "type": "smørrebrød", "beskrivelse": "Smørrebrød siden 1877.", "pris": "100-200 DKK", "latitude": 55.6833, "longitude": 12.5739},
    {"navn": "Neckarmüller", "land": "Tyskland", "by": "Tübingen", "type": "tysk", "beskrivelse": "Bryggeri ved Neckar.", "pris": "€10-20", "latitude": 48.5197, "longitude": 9.0583},
    {"navn": "Schlenkerla", "land": "Tyskland", "by": "Bamberg", "type": "tysk", "beskrivelse": "Røykøl siden 1405.", "pris": "€8-15", "latitude": 49.8917, "longitude": 10.8847},
    {"navn": "Zur Letzten Instanz", "land": "Tyskland", "by": "Berlin", "type": "tysk", "beskrivelse": "Berlins eldste. 1621.", "pris": "€15-30", "latitude": 52.5164, "longitude": 13.4147},
    {"navn": "Konnopke's Imbiss", "land": "Tyskland", "by": "Berlin", "type": "streetfood", "beskrivelse": "Currywurst.", "pris": "€3-5", "latitude": 52.5414, "longitude": 13.4119},
    {"navn": "Café Central", "land": "Østerrike", "by": "Wien", "type": "kafé", "beskrivelse": "Trotskij og Freud.", "pris": "€8-15", "latitude": 48.2103, "longitude": 16.3654},
    {"navn": "Gmoakeller", "land": "Østerrike", "by": "Wien", "type": "østerriksk", "beskrivelse": "Gammel vinkjeller.", "pris": "€15-25", "latitude": 48.2017, "longitude": 16.3789},
    {"navn": "Koliba U Deda", "land": "Slovakia", "by": "Martin", "type": "slovakisk", "beskrivelse": "Fjellmat.", "pris": "€5-12", "latitude": 49.0614, "longitude": 18.9167},
    {"navn": "Café Veronský dom", "land": "Slovakia", "by": "Martin", "type": "kafé", "beskrivelse": "Middelalderkafé.", "pris": "€3-6", "latitude": 49.0681, "longitude": 18.9222},
    {"navn": "Casa Tomis", "land": "Romania", "by": "Constanța", "type": "sjømat", "beskrivelse": "Fersk fisk.", "pris": "€8-20", "latitude": 44.1714, "longitude": 28.6606},
    {"navn": "Crama Sibiul Vechi", "land": "Romania", "by": "Sibiu", "type": "rumensk", "beskrivelse": "Transylvansk kjeller.", "pris": "€8-15", "latitude": 45.7958, "longitude": 24.1506},
    {"navn": "Caru' cu Bere", "land": "Romania", "by": "Bukarest", "type": "rumensk", "beskrivelse": "Ølhus fra 1879.", "pris": "€10-25", "latitude": 44.4322, "longitude": 26.0981},
    {"navn": "Café Louvre", "land": "Tsjekkia", "by": "Praha", "type": "kafé", "beskrivelse": "Einstein og Kafka.", "pris": "€5-10", "latitude": 50.0822, "longitude": 14.4186},
    {"navn": "Hanácká Hospoda", "land": "Tsjekkia", "by": "Olomouc", "type": "tsjekkisk", "beskrivelse": "Stinkende ost.", "pris": "€5-10", "latitude": 49.5947, "longitude": 17.2522},
    {"navn": "New York Café", "land": "Ungarn", "by": "Budapest", "type": "kafé", "beskrivelse": "Verdens vakreste.", "pris": "€10-20", "latitude": 47.5025, "longitude": 19.0733},
    {"navn": "Bors GasztroBár", "land": "Ungarn", "by": "Budapest", "type": "streetfood", "beskrivelse": "Supper.", "pris": "€3-6", "latitude": 47.5014, "longitude": 19.0642},
    {"navn": "Café Majestic", "land": "Portugal", "by": "Porto", "type": "kafé", "beskrivelse": "Belle Époque.", "pris": "€5-12", "latitude": 41.1472, "longitude": -8.6067},
    {"navn": "Café A Brasileira", "land": "Portugal", "by": "Lisboa", "type": "kafé", "beskrivelse": "Pessoas kafé.", "pris": "€3-8", "latitude": 38.7106, "longitude": -9.1419},
    {"navn": "Bodega de la Ardosa", "land": "Spania", "by": "Madrid", "type": "tapas", "beskrivelse": "Tapasbar 1892.", "pris": "€5-15", "latitude": 40.4239, "longitude": -3.7025},
    {"navn": "El Rinconcillo", "land": "Spania", "by": "Sevilla", "type": "tapas", "beskrivelse": "Spanias eldste.", "pris": "€5-15", "latitude": 37.3931, "longitude": -5.9886},
    {"navn": "La Favorita", "land": "Italia", "by": "Bologna", "type": "italiensk", "beskrivelse": "Uten meny.", "pris": "€15-25", "latitude": 44.4939, "longitude": 11.3428},
    {"navn": "Trattoria da Enzo", "land": "Italia", "by": "Roma", "type": "italiensk", "beskrivelse": "Hemmelig.", "pris": "€15-25", "latitude": 41.8881, "longitude": 12.4786},
    {"navn": "All'Arco", "land": "Italia", "by": "Roma", "type": "streetfood", "beskrivelse": "Cicchetti.", "pris": "€5-10", "latitude": 41.8902, "longitude": 12.4922},
    {"navn": "Le Petit Zinc", "land": "Frankrike", "by": "Paris", "type": "fransk", "beskrivelse": "Art nouveau.", "pris": "€20-35", "latitude": 48.8539, "longitude": 2.3353},
    {"navn": "Chez Janou", "land": "Frankrike", "by": "Paris", "type": "fransk", "beskrivelse": "Sjokolademousse.", "pris": "€20-35", "latitude": 48.8558, "longitude": 2.3667},
    {"navn": "À la Mort Subite", "land": "Belgia", "by": "Brussel", "type": "kafé", "beskrivelse": "Historisk ølkafé.", "pris": "€5-12", "latitude": 50.8483, "longitude": 4.3564},
    {"navn": "The George Inn", "land": "Storbritannia", "by": "London", "type": "pub", "beskrivelse": "Shakespeare drakk her.", "pris": "£10-20", "latitude": 51.5042, "longitude": -0.0911},
    {"navn": "Kehoe's Pub", "land": "Irland", "by": "Dublin", "type": "pub", "beskrivelse": "Urørt siden 1800.", "pris": "€10-20", "latitude": 53.3417, "longitude": -6.2592},
    {"navn": "Tima-Irma", "land": "Bosnia", "by": "Mostar", "type": "bosnisk", "beskrivelse": "Familierestaurant.", "pris": "€5-10", "latitude": 43.3369, "longitude": 17.8153}
]