# database.py

# ========================================
# DATABASE – 70+ SKJULTE PERLER (MED KARTKOORDINATER)
# ========================================
SKJULTE_PERLER = [
    # ========== SVERIGE ==========
    {"navn": "Håveruds akvedukt", "land": "Sverige", "by": "Håverud", "type": "arkitektur", "beskrivelse": "Ingeniøranlegg i Dalsland der Dalslands kanal krysser over vei og jernbane i en synlig stålkonstruksjon.", "tips": "Stå under akvedukten når en båt passerer for å se konstruksjonen i bruk.", "beste_tid": "mai-september", "latitude": 58.8222, "longitude": 12.4131},
    {"navn": "Borgvattnets Prästgård", "land": "Sverige", "by": "Borgvattnet", "type": "overnaturlig", "beskrivelse": "Historisk prestegård i Jämtland som er kjent i Sverige for fortellinger om uforklarlige hendelser.", "tips": "Bestill overnatting på forhånd om du vil oppleve stedet etter stengetid.", "beste_tid": "hele året", "latitude": 63.4211, "longitude": 15.8544},
    {"navn": "Gropens bilkyrkogård", "land": "Sverige", "by": "Ryd", "type": "urbanexploring", "beskrivelse": "Skogsområde med eldre biler fra midten av 1900-tallet, gradvis overgrodd av mose og trær.", "tips": "Fotografer tidlig på dagen når lyset er mykt mellom trærne.", "beste_tid": "mai-september", "latitude": 56.4647, "longitude": 14.6547},
    {"navn": "Nämforsens hällristningar", "land": "Sverige", "by": "Näsåker", "type": "historie", "beskrivelse": "Et av Nord-Europas viktigste felt med helleristninger, med tusenvis av motiver fra steinalderen.", "tips": "Bruk lokal guide for å forstå symbolene og historien bak motivene.", "beste_tid": "mai-september", "latitude": 63.4414, "longitude": 16.8858},
    {"navn": "Bjuröklubb", "land": "Sverige", "by": "Lövånger", "type": "natur", "beskrivelse": "Utsatt odde ved Bottenviken med fyr, svaberg og vid havutsikt i et rolig kystlandskap.", "tips": "Overnatt i fyrvokterboligen om du vil ha kveld og morgen nesten for deg selv.", "beste_tid": "juni-juli", "latitude": 64.4811, "longitude": 21.5714},
    {"navn": "Skuleskogen", "land": "Sverige", "by": "Docksta", "type": "natur", "beskrivelse": "Nasjonalpark i Höga Kusten med urskog, bratte kystberg og den dype kløften Slåttdalsskrevan.", "tips": "Ta rundløype via Slåttdalsskrevan og utsiktspunktene mot kysten.", "beste_tid": "mai-september", "latitude": 63.1194, "longitude": 18.4917},
    {"navn": "Ales stenar", "land": "Sverige", "by": "Kåseberga", "type": "historie", "beskrivelse": "Steinsetting fra jernalderen på en høyde over Østersjøen, ofte sammenlignet med Stonehenge i skala og mystikk.", "tips": "Kom tidlig eller sent for roligere stemning og godt lys over kysten.", "beste_tid": "hele året", "latitude": 55.3828, "longitude": 14.0544},
    {"navn": "Sarek nasjonalpark", "land": "Sverige", "by": "Jokkmokk", "type": "natur", "beskrivelse": "Stor fjellpark uten turisthytter i nasjonalparken, kjent for vill natur, dalfører og krevende ruter.", "tips": "Passer best for erfarne fjellvandrere med solid plan og egen sikkerhetsmargin.", "beste_tid": "juli-august", "latitude": 67.2833, "longitude": 17.5333},
    # ========== NORGE ==========
    {"navn": "Pyramiden", "land": "Norge", "by": "Svalbard", "type": "spøkstad", "beskrivelse": "Tidligere sovjetisk gruvebosetning på Svalbard, bevart som et sjeldent innblikk i arktisk industrihistorie.", "tips": "Bli med autorisert guidet tur fra Longyearbyen for trygg transport og historisk kontekst.", "beste_tid": "juni-august", "latitude": 78.6564, "longitude": 16.3244},
    {"navn": "Røros", "land": "Norge", "by": "Røros", "type": "kultur", "beskrivelse": "Verdensarvby med trehusbebyggelse og gruvehistorie fra 1600-tallet, med tydelig fjellbypreg hele året.", "tips": "Kombiner byvandring med lokalmat og et besøk i bergstadenes historiske områder.", "beste_tid": "februar, juli", "latitude": 62.5747, "longitude": 11.3842},
    {"navn": "Urnes stavkirke", "land": "Norge", "by": "Urnes", "type": "historie", "beskrivelse": "UNESCO-listet stavkirke fra middelalderen med utskårne detaljer som viser overgangen fra norrøn til kristen kunsttradisjon.", "tips": "Ta ferge over Lustrafjorden og kombiner besøket med utsiktspunktene i området.", "beste_tid": "mai-september", "latitude": 61.2981, "longitude": 7.3222},
    # ========== DANMARK ==========
    {"navn": "Rubjerg Knude Fyr", "land": "Danmark", "by": "Løkken", "type": "natur", "beskrivelse": "Historisk fyr på Jyllandskysten flyttet innlands etter kraftig kysterosjon og vandrende sanddyner.", "tips": "Sjekk vindforhold og gå turen over sanddynene for utsikt mot havet.", "beste_tid": "hele året", "latitude": 57.4485, "longitude": 9.7749},
    {"navn": "Christiania", "land": "Danmark", "by": "København", "type": "kultur", "beskrivelse": "Etablert alternativ bydel i København med egen historie, kreativt miljø og tydelig lokal kulturdebatt.", "tips": "Bli med på organisert omvisning for å forstå området utover førsteinntrykket.", "beste_tid": "hele året", "latitude": 55.6733, "longitude": 12.5997},
    # ========== FINLAND ==========
    {"navn": "Klippekirken", "land": "Finland", "by": "Helsinki", "type": "arkitektur", "beskrivelse": "Moderne kirke sprengt direkte inn i fjell, kjent for naturlig lys og god akustikk.", "tips": "Sjekk om det er konsert eller korøvelse for å oppleve akustikken på sitt beste.", "beste_tid": "hele året", "latitude": 60.1731, "longitude": 24.9253},
    {"navn": "Bomarsunds festning", "land": "Finland", "by": "Åland", "type": "historie", "beskrivelse": "Ruiner etter en stor russisk festning fra 1800-tallet, ødelagt under Krimkrigen.", "tips": "Lei sykkel eller bil for å se både hovedområdet og de spredte skansene.", "beste_tid": "mai-september", "latitude": 60.2125, "longitude": 20.2378},
    # ========== TYSKLAND ==========
    {"navn": "Rakotzbrücke", "land": "Tyskland", "by": "Kromlau", "type": "arkitektur", "beskrivelse": "Historisk bro i Kromlauer Park utformet slik at den danner en nesten full sirkel i vannspeilet.", "tips": "Besøk tidlig på dagen når vannet er roligere for best speiling.", "beste_tid": "mai-oktober", "latitude": 51.5363, "longitude": 14.6405},
    {"navn": "Görlitz", "land": "Tyskland", "by": "Görlitz", "type": "kultur", "beskrivelse": "By ved grensen til Polen med svært godt bevart bebyggelse fra ulike epoker og lite masseturisme.", "tips": "Ta byvandring gjennom gamlebyen og kryss broen til Zgorzelec for toland-opplevelse.", "beste_tid": "mai-september", "latitude": 51.1528, "longitude": 14.9872},
    {"navn": "Beelitz-Heilstätten", "land": "Tyskland", "by": "Beelitz", "type": "urbanexploring", "beskrivelse": "Tidligere sanatorium- og sykehusområde sør for Berlin, kjent for murarkitektur og historisk trebrosti over området.", "tips": "Velg offisiell omvisning for trygg ferdsel og mer historisk bakgrunn.", "beste_tid": "april-oktober", "latitude": 52.2619, "longitude": 12.9197},
    {"navn": "Bamberg", "land": "Tyskland", "by": "Bamberg", "type": "gastronomi", "beskrivelse": "Verdensarvby med historisk sentrum og sterk ølkultur, særlig kjent for lokal røykøltradisjon.", "tips": "Prøv et glass Rauchbier i den eldre delen av byen og gå deretter langs Regnitz.", "beste_tid": "hele året", "latitude": 49.8917, "longitude": 10.8917},
    {"navn": "Wünsdorf bunkerstadt", "land": "Tyskland", "by": "Wünsdorf", "type": "urbanexploring", "beskrivelse": "Område sør for Berlin med underjordiske bunkere og rester av tidligere sovjetisk militær tilstedeværelse.", "tips": "Book guidet tur i bunkeranleggene for tilgang til de mest interessante delene.", "beste_tid": "april-oktober", "latitude": 52.1931, "longitude": 13.4683},
    # ========== ØSTERRIKE ==========
    # ========== SLOVAKIA ==========
    {"navn": "Spišské Podhradie", "land": "Slovakia", "by": "Spišské Podhradie", "type": "kultur", "beskrivelse": "Liten historisk by ved foten av Spiš-slottet, et av de største borgkompleksene i Sentral-Europa.", "tips": "Gå opp tidlig eller sent for roligere lys over borgområdet.", "beste_tid": "mai-september", "latitude": 48.9994, "longitude": 20.7519},
    {"navn": "Martin", "land": "Slovakia", "by": "Martin", "type": "kultur", "beskrivelse": "By med sterk rolle i slovakisk kulturhistorie, omgitt av fjell og med nærhet til Malá Fatra.", "tips": "Kombiner museumsbesøk i byen med en dagstur til turstier i Malá Fatra.", "beste_tid": "mai-september", "latitude": 49.0650, "longitude": 18.9219},
    {"navn": "Banská Bystrica", "land": "Slovakia", "by": "Banská Bystrica", "type": "kultur", "beskrivelse": "Tidligere gruve- og handelsby med stort torg, fargerike fasader og viktig moderne krigshistorie.", "tips": "Besøk SNP-museet for å forstå byens rolle under andre verdenskrig.", "beste_tid": "mai-september", "latitude": 48.7389, "longitude": 19.1497},
    {"navn": "Čičmany", "land": "Slovakia", "by": "Čičmany", "type": "kultur", "beskrivelse": "Landsby kjent for tradisjonelle trehus dekorert med hvite, geometriske mønstre i folkekunststil.", "tips": "Gå mellom husene til fots og les om symbolikken i mønstrene på stedet.", "beste_tid": "mai-september", "latitude": 48.9556, "longitude": 18.5164},
    # ========== ROMANIA ==========
    {"navn": "Băile Tușnad", "land": "Romania", "by": "Băile Tușnad", "type": "natur", "beskrivelse": "Liten kurby i Karpatene med mineralrike kilder og nærhet til vulkanske landskap rundt Saint Anne-sjøen.", "tips": "Besøk innsjøen tidlig på dagen og bruk lokale guider der dyreliv kan forekomme.", "beste_tid": "juni-september", "latitude": 46.1461, "longitude": 25.8603},
    {"navn": "Maramureș", "land": "Romania", "by": "Maramureș", "type": "kultur", "beskrivelse": "Region med levende landsbytradisjoner, treskurd, trekirker og et roligere tempo enn Romanias storbyer.", "tips": "Besøk både trekirkene og lokale håndverkere for en mer helhetlig opplevelse.", "beste_tid": "mai-september", "latitude": 47.6581, "longitude": 24.0628},
    {"navn": "Sibiu", "land": "Romania", "by": "Sibiu", "type": "kultur", "beskrivelse": "Historisk transilvansk by med godt bevart sentrum, brosteinsgater og de karakteristiske 'øyne'-vinduene i takene.", "tips": "Ta en kveldsvandring i gamlebyen og avslutt med lokal mat i kjellerrestaurantene.", "beste_tid": "mai-september", "latitude": 45.7983, "longitude": 24.1256},
    # ========== TSJEKKIA ==========
    {"navn": "Olomouc", "land": "Tsjekkia", "by": "Olomouc", "type": "kultur", "beskrivelse": "Universitetsby med barokk arkitektur, historiske torg og en mer lokal atmosfære enn de mest besøkte storbyene.", "tips": "Se den astronomiske klokken og gå mellom fontenene i gamlebyen.", "beste_tid": "april-oktober", "latitude": 49.5939, "longitude": 17.2508},
    {"navn": "Český Krumlov i november", "land": "Tsjekkia", "by": "Český Krumlov", "type": "kultur", "beskrivelse": "Velbevart middelalderby som oppleves roligere i senhøst, med tåke over elven og færre dagsbesøkende.", "tips": "Overnatt i sentrum for å oppleve byen tidlig morgen og sen kveld.", "beste_tid": "november", "latitude": 48.8128, "longitude": 14.3145},
    {"navn": "Kutná Hora", "land": "Tsjekkia", "by": "Kutná Hora", "type": "historie", "beskrivelse": "Tidligere sølvby med UNESCO-status, kjent for St. Barbara-katedralen og beinkapellet i Sedlec.", "tips": "Kjøp kombinasjonsbillett og sett av tid til både sentrum og Sedlec-området.", "beste_tid": "hele året", "latitude": 49.9519, "longitude": 15.2678},
    # ========== UNGARN ==========
    {"navn": "Pécs", "land": "Ungarn", "by": "Pécs", "type": "kultur", "beskrivelse": "Sørungarsk by med romerske og osmanske spor, levende studentmiljø og mange kulturarenaer.", "tips": "Kombiner Zsolnay-kvartalet med byvandring i de eldste gatene.", "beste_tid": "april-oktober", "latitude": 46.0728, "longitude": 18.2322},
    {"navn": "Egersalók", "land": "Ungarn", "by": "Egersalók", "type": "natur", "beskrivelse": "Kurbadområde kjent for hvite kalkavsetninger fra varme kilder og termalbad i åssiden.", "tips": "Besøk sent på ettermiddagen for roligere bad og mykere lys.", "beste_tid": "hele året", "latitude": 47.8547, "longitude": 20.3325},
    # ========== POLEN ==========
    {"navn": "Krzywy Las", "land": "Polen", "by": "Gryfino", "type": "natur", "beskrivelse": "Liten furuskog med uvanlig buede trestammer, et naturfenomen som fortsatt diskuteres.", "tips": "Kom i dis eller lav kveldssol for tydeligere former i fotografier.", "beste_tid": "hele året", "latitude": 53.2139, "longitude": 14.4750},
    # ========== BALTIKUM ==========
    {"navn": "Korshøyden", "land": "Litauen", "by": "Šiauliai", "type": "kultur", "beskrivelse": "Pilegrims- og minnested med svært mange kors satt opp gjennom flere generasjoner som symbol på tro og motstand.", "tips": "Respekter stedet som minneområde og bruk tid på å lese historien på informasjonstavlene.", "beste_tid": "hele året", "latitude": 56.0153, "longitude": 23.4164},
    {"navn": "Tartu", "land": "Estland", "by": "Tartu", "type": "kultur", "beskrivelse": "Estlands universitetsby med kreativt miljø, kompakt sentrum og en tydelig studentpreget kultur.", "tips": "Stikk innom Aparaaditehas for kunst, mat og lokale arrangementer.", "beste_tid": "mai-september", "latitude": 58.3780, "longitude": 26.7290},
    {"navn": "Kuldīga", "land": "Latvia", "by": "Kuldīga", "type": "natur", "beskrivelse": "Historisk småby ved Venta-fossen, kjent for bredt fosseparti og trearkitektur i sentrum.", "tips": "Gå langs elvepromenaden og se fossen fra flere utkikkspunkter.", "beste_tid": "mai-september", "latitude": 56.9678, "longitude": 21.9722},
    # ========== PORTUGAL ==========
    {"navn": "Monsaraz", "land": "Portugal", "by": "Monsaraz", "type": "kultur", "beskrivelse": "Befestet åslandsby i Alentejo med hvitkalkede hus, bymurer og vid utsikt over innsjøen Alqueva.", "tips": "Bli til etter mørkets frembrudd for stjernehimmel i et område med lite lysforurensning.", "beste_tid": "april-oktober", "latitude": 38.4436, "longitude": -7.3811},
    # ========== SPANIA ==========
    {"navn": "Castellfollit de la Roca", "land": "Spania", "by": "Castellfollit", "type": "natur", "beskrivelse": "Landsby bygget langs en smal basaltklippe over dalen, med dramatisk silhuett i vulkansk landskap.", "tips": "Se klippen fra utsiktspunktet nedenfor før du går opp i gamlebyen.", "beste_tid": "mars-november", "latitude": 42.2192, "longitude": 2.5539},
    {"navn": "Las Médulas", "land": "Spania", "by": "Las Médulas", "type": "natur", "beskrivelse": "Rødlig landskap formet av romersk gullutvinning, med stier, grotter og særpregede jordformasjoner.", "tips": "Ta ruten til Mirador de Orellán for best oversikt over området.", "beste_tid": "april-oktober", "latitude": 42.4606, "longitude": -6.7686},
    # ========== ITALIA ==========
    {"navn": "Matera om natten", "land": "Italia", "by": "Matera", "type": "kultur", "beskrivelse": "Sør-italiensk by kjent for Sassi-distriktene med huleboliger og steinarkitektur med svært lange historiske røtter.", "tips": "Overnatt i grottehotell og gå kveldsvandring når området er opplyst.", "beste_tid": "april-oktober", "latitude": 40.6667, "longitude": 16.6000},
    {"navn": "Civita di Bagnoregio", "land": "Italia", "by": "Civita", "type": "kultur", "beskrivelse": "Liten klippeby i Lazio med begrenset adkomst via gangbro og tydelige spor av erosjon rundt platået.", "tips": "Kom tidlig for å krysse broen før de største besøksgruppene.", "beste_tid": "april-oktober", "latitude": 42.6278, "longitude": 12.1136},
    {"navn": "Craco", "land": "Italia", "by": "Craco", "type": "spøkstad", "beskrivelse": "Forlatt åsby i Basilicata, delvis evakuert etter jordskred, med ruiner og tydelig middelalderpreg.", "tips": "Besøk med godkjent guide siden store deler av byen er sperret av sikkerhetshensyn.", "beste_tid": "april-oktober", "latitude": 40.3789, "longitude": 16.4411},
    # ========== BALKAN ==========
    {"navn": "Mostar etter 17", "land": "Bosnia", "by": "Mostar", "type": "kultur", "beskrivelse": "Historisk by ved Neretva med osmansk arv, brokultur og roligere stemning i timene etter dagsturtrafikken.", "tips": "Se gamlebroen i kveldsljus og spis lokalt i sidegatene ved elven.", "beste_tid": "mai-september", "latitude": 43.3433, "longitude": 17.8081},
    {"navn": "Ohridsjøen", "land": "Nord-Makedonia", "by": "Ohrid", "type": "natur", "beskrivelse": "Dyp innsjø med høy biologisk verdi og lang kulturhistorie, delt mellom Nord-Makedonia og Albania.", "tips": "Ta båttur til St. Naum og sett av tid til gamlebyen i Ohrid.", "beste_tid": "mai-september", "latitude": 41.1139, "longitude": 20.8028},
    {"navn": "Gjirokastër", "land": "Albania", "by": "Gjirokastër", "type": "kultur", "beskrivelse": "UNESCO-listet steinby med ottomansk preg, bratte gater og store historiske hus.", "tips": "Bo i tradisjonelt steinhus og besøk borgen for utsikt over Drino-dalen.", "beste_tid": "mai-september", "latitude": 40.0758, "longitude": 20.1389},
    {"navn": "Prizren", "land": "Kosovo", "by": "Prizren", "type": "kultur", "beskrivelse": "Kulturby med osmansk arkitektur, elvepromenade og livlig kaféliv rundt gamlebyen.", "tips": "Ta turen opp til festningen før solnedgang og avslutt i sentrum.", "beste_tid": "mai-september", "latitude": 42.2139, "longitude": 20.7397},
    # ========== BULGARIA ==========
    {"navn": "Buzludzha", "land": "Bulgaria", "by": "Buzludzha", "type": "urbanexploring", "beskrivelse": "Monument på en fjelltopp fra kommunisttiden, kjent for sin futuristiske form og monumentale mosaikker.", "tips": "Ta med varme klær og sjekk tilgangsregler, siden forholdene kan endre seg raskt.", "beste_tid": "juni-september", "latitude": 42.7358, "longitude": 25.3244},
    # ========== FRANKRIKE ==========
    {"navn": "Les Machines de l'Île", "land": "Frankrike", "by": "Nantes", "type": "museum", "beskrivelse": "Kunst- og ingeniørprosjekt i Nantes med store mekaniske skapninger inspirert av Jules Verne og industrihistorie.", "tips": "Book tidlig hvis du vil kjøre den store mekaniske elefanten.", "beste_tid": "hele året", "latitude": 47.2064, "longitude": -1.5642},
    {"navn": "Rochefort-en-Terre", "land": "Frankrike", "by": "Rochefort-en-Terre", "type": "kultur", "beskrivelse": "Landsby i Bretagne med steinhus, blomsterpregede gater og kompakt historisk sentrum.", "tips": "Besøk i blomstersesongen og bli til kvelds når gatene er roligere.", "beste_tid": "mai-september", "latitude": 47.6997, "longitude": -2.3367},
    # ========== BENELUX ==========
    {"navn": "Durbuy", "land": "Belgia", "by": "Durbuy", "type": "kultur", "beskrivelse": "Kompakt Ardenner-by med brosteinsgater, steinfasader og sterke mattradisjoner i liten skala.", "tips": "Utforsk sentrum til fots og avslutt med lokal sjokolade eller øl.", "beste_tid": "mai-september", "latitude": 50.3522, "longitude": 5.4561},
    {"navn": "Groningen", "land": "Nederland", "by": "Groningen", "type": "kultur", "beskrivelse": "Livlig universitetsby med tydelig sykkelkultur, kanaler og moderne byliv rundt historiske bygg.", "tips": "Lei sykkel for å oppleve både sentrum og kanalområdene effektivt.", "beste_tid": "april-oktober", "latitude": 53.2194, "longitude": 6.5665},
    # ========== STORBRITANNIA/IRLAND ==========
    {"navn": "Skellig Michael", "land": "Irland", "by": "Skellig", "type": "historie", "beskrivelse": "Bratt klippeøy med tidligkristent klosteranlegg fra tidlig middelalder og dramatisk Atlanterhavsnatur.", "tips": "Bestill båttur tidlig i sesongen, siden vær og kapasitet begrenser avgangene.", "beste_tid": "mai-september", "latitude": 51.7719, "longitude": -10.5392},
    {"navn": "Portmeirion", "land": "Storbritannia", "by": "Portmeirion", "type": "kultur", "beskrivelse": "Planlagt landsby i Nord-Wales med middelhavsinspirert arkitektur, hager og særpreget designhistorie.", "tips": "Overnatt i området for å oppleve landsbyen før dagsturene starter.", "beste_tid": "mai-september", "latitude": 52.9133, "longitude": -4.0994},
    {"navn": "Paldiski","by": "Paldiski","land": "Estland","type": "eventyr","latitude": 59.3512,"longitude": 24.0531,"beskrivelse": "En tidligere topphemmelig, lukket sovjetisk militærby på en vakker halvøy. Her lå det største treningssenteret for kjernefysiske ubåter i hele Sovjetunionen, og vanlige folk fikk ikke engang reise inn hit uten spesialtillatelse før i 1994. I dag er det et fascinerende, rått og spøkelsesaktig sted med forlatte kaserner, spektakulære kalksteinsklipper og et vakkert, rødt fyrtårn.","tips": "Klatre opp i fyrtårnet på Pakri-odden for en vill utsikt over Finskebukta.","pris": "€"},
    {"navn": "Deventer","by": "Deventer","land": "Nederland","type": "kultur","latitude": 52.2561,"longitude": 6.1604,"beskrivelse": "Glem overfylte Amsterdam! Deventer er en av de aller eldste byene i Nederland, vakkert plassert langs elven IJssel. Byen har en perfekt bevart middelalderkjerne med trange, svingete smug, urgamle mursteinshus og en herlig, tilbakelent atmosfære fri for turisthorder.","tips": "Smak på den tradisjonelle honningkaken 'Deventer Koek' på det historiske torget Brink.","pris": "€€"},
    {"navn": "Pitigliano","by": "Pitigliano","land": "Italia","type": "kultur","latitude": 42.6344,
    "longitude": 11.6675,"beskrivelse": "Ofte kalt 'Lille Jerusalem'. Dette er en spektakulær by i Toscana som er hugget direkte ut av en enorm klippe av vulkansk tuffstein. Husene ser ut som de vokser organisk opp fra fjellet. Byen er omringet av 'Vie Cave' – mystiske, dype og eldgamle veier som etruskerne hugget dypt ned i fjellet for over 2000 år siden.","tips": "Gå en tur i de svale etruskiske huleveiene (Vie Cave) som ligger like utenfor byporten.","pris": "€€"},
    {"navn": "Sala Silvergruva","by": "Sala","land": "Sverige","type": "eventyr","latitude": 59.9075,"longitude": 16.5702,
    "beskrivelse": "En av verdens best bevarte gruvemiljøer. I over 500 år var dette en av Sveriges viktigste sølvgruver. Det mest helsprø her er at de har bygget en hotellsuite – 'Gruvsviten' – hele 155 meter under bakken! Her sover du i et oppvarmet rom omringet av mørke, underjordiske sjakter og opplyste, mystiske gruvesjøer.","tips": "Ta med varme klær; det er rundt 2 plussgrader i gruvegangene, selv om hotellrommet heldigvis er godt oppvarmet.","pris": "€€€"},
    {"navn": "Bergen (Germany)", "by": "Bergen (Germany)", "land": "Tyskland", "type": "kultur", "latitude": 52.8103, "longitude": 9.9611, "beskrivelse": "Liten by i Niedersachsen med historisk sentrum, tradisjonelle bindingsverkshus og nærhet til Lüneburger Heide.", "tips": "Kombiner byvandring med en dagstur i hedelandskapet rundt byen.", "pris": "€"},
    {"navn": "Orford Ness", "by": "Orford Ness", "land": "Storbritannia", "type": "kultur", "latitude": 52.0814, "longitude": 1.5586, "beskrivelse": "Avsidesliggende kysttange i Suffolk med tidligere militære testområder, radiohistorie og et særpreget naturreservat.", "tips": "Sjekk båttider og åpningstider på forhånd, siden adkomst styres av vær og sesong.", "pris": "€"},
    {"navn": "Imber", "by": "Imber", "land": "Storbritannia", "type": "kultur", "latitude": 51.234, "longitude": -2.051, "beskrivelse": "Forlatt landsby på Salisbury Plain som ble evakuert under andre verdenskrig og kun åpnes for besøk enkelte dager i året.", "tips": "Besøk når området er åpent for publikum, og planlegg transport i forkant.", "pris": "€"},
    {"navn": "Tyneham", "by": "Tyneham", "land": "Storbritannia", "type": "kultur", "latitude": 50.623, "longitude": -2.169, "beskrivelse": "Historisk landsby i Dorset som ble fraflyttet i 1943 og bevart som et tidsbilde av krigstidens Storbritannia.", "tips": "Kombiner landsbyen med tur til Worbarrow Bay når stiene er åpne.", "pris": "€"},
    {"navn": "Stroma", "by": "Stroma", "land": "Storbritannia", "type": "kultur", "latitude": 58.68, "longitude": -3.12, "beskrivelse": "Avfolket øy i Pentland Firth med forblåste ruiner, sjøfugl og dramatisk utsikt mot Nord-Skottland.", "tips": "Velg guidet båttur med lokalkjent skipper for tryggest og mest lærerik opplevelse.", "pris": "€"},
    {"navn": "Scapa Flow", "by": "Scapa Flow", "land": "Storbritannia", "type": "kultur", "latitude": 58.9, "longitude": -3.05, "beskrivelse": "Stor naturhavn på Orknøyene med sentral maritim historie fra begge verdenskriger og kjente vrakområder.", "tips": "Besøk gjerne med guide eller museumstopp i Kirkwall for historisk kontekst.", "pris": "€"},
    {"navn": "Prora", "by": "Prora", "land": "Tyskland", "type": "kultur", "latitude": 54.4389, "longitude": 13.575, "beskrivelse": "Langstrakt kystanlegg fra 1930-tallet på Rügen, i dag delvis museum og delvis ombygd til nye formål.", "tips": "Sett av tid til dokumentasjonssenteret for bakgrunn om anleggets opprinnelse og etterbruk.", "pris": "€"},
    {"navn": "Teufelsberg", "by": "Teufelsberg", "land": "Tyskland", "type": "kultur", "latitude": 52.4977, "longitude": 13.2429, "beskrivelse": "Kunst- og utsiktspunkt i Berlin på et kunstig fjell med rester av en tidligere lyttepost fra den kalde krigen.", "tips": "Besøk i klart vær for panoramautsikt over byen og best fotolys.", "pris": "€"},
    {"navn": "Kelvedon Hatch Secret Nuclear Bunker", "by": "Kelvedon Hatch Secret Nuclear Bunker", "land": "Storbritannia", "type": "kultur", "latitude": 51.6718, "longitude": 0.2566, "beskrivelse": "Tidligere britisk atomkommandobunker i Essex, bevart med kontrollrom, sambandsutstyr og beredskapsområder.", "tips": "Bruk audioguide for å få med detaljene om bunkerens rolle under den kalde krigen.", "pris": "€"},
    {"navn": "Dunmore Pineapple", "by": "Dunmore Pineapple", "land": "Storbritannia", "type": "kultur", "latitude": 56.0767, "longitude": -3.7867, "beskrivelse": "Særegen 1700-tallspaviljong i Skottland med ikonisk ananasformet kuppel, omgitt av historisk parklandskap.", "tips": "Kombiner besøket med en rolig spasertur i skogsområdene rundt godset.", "pris": "€"},
    {"navn": "Heeresversuchsanstalt Peenemünde", "by": "Heeresversuchsanstalt Peenemünde", "land": "Tyskland", "type": "kultur", "latitude": 54.1482, "longitude": 13.794, "beskrivelse": "Tidligere forskningsområde på Usedom med tung krigshistorie, i dag museum med utstillinger om teknologi og etikk.", "tips": "Besøk teknisk museum og dokumentasjonssenter for helhetlig forståelse.", "pris": "€"},
    {"navn": "Pluckley", "by": "Pluckley", "land": "Storbritannia", "type": "kultur", "latitude": 51.1761, "longitude": 0.7578, "beskrivelse": "Landsby i Kent med flere historiske bygninger, gamle kirkelandskap og lokal folklore knyttet til området.", "tips": "Gå en rolig rundtur gjennom landsbyen og innom kirken for lokalhistorie.", "pris": "€"},
    {"navn": "Waldspirale", "by": "Waldspirale", "land": "Tyskland", "type": "kultur", "latitude": 49.8856, "longitude": 8.6558, "beskrivelse": "Fargerikt boligbygg i Darmstadt tegnet av Friedensreich Hundertwasser, kjent for bølgende linjer og uvanlige detaljer.", "tips": "Se bygget fra flere vinkler og kombiner med en arkitekturvandring i området.", "pris": "€"},
    {"navn": "Reschensee", "by": "Reschensee", "land": "Italia", "type": "kultur", "latitude": 46.801, "longitude": 10.531, "beskrivelse": "Alpin innsjø i Sør-Tirol kjent for kirketårnet som stikker opp av vannet etter neddemming på 1950-tallet.", "tips": "Besøk tidlig morgen eller kveld for roligere stemning og bedre lys til bilder.", "pris": "€"},
    # ========== HISTORISKE OG SÆRPREGEDE STEDER ==========
    {"navn": "Maunsell Forts", "by": "Maunsell Forts", "land": "Storbritannia", "type": "kultur", "latitude": 51.4667, "longitude": 1.1000, "beskrivelse": "Forlatte flåtefort fra andre verdenskrig i Nordsjøen, bygget for å forsvare London mot tyske fly.", "tips": "Båtutflukt fra Whitstable eller Southend-on-Sea.", "pris": "€"},
    {"navn": "The Forbidden Corner", "by": "The Forbidden Corner", "land": "Storbritannia", "type": "kultur", "latitude": 54.2800, "longitude": -1.8800, "beskrivelse": "En særegen labyrint av tunneler, hager og skjulte rom i Yorkshire Dales.", "tips": "Book billett på forhånd – det er ofte utsolgt.", "pris": "€€"},
    {"navn": "Spreepark", "by": "Spreepark", "land": "Tyskland", "type": "kultur", "latitude": 52.4875, "longitude": 13.4611, "beskrivelse": "Forlatt fornøyelsespark i Berlin, stengt siden 2002, med rustne karuseller og overgrodd natur.", "tips": "Guidet tur er eneste måte å komme inn på.", "pris": "€"},
    {"navn": "Regierungsbunker", "by": "Regierungsbunker", "land": "Tyskland", "type": "kultur", "latitude": 50.5833, "longitude": 7.2167, "beskrivelse": "Hemmelig tysk regjeringsbunker fra den kalde krigen, bygget for å huse regjeringen i tilfelle atomkrig.", "tips": "Museum i Ahrweiler – guidet tur anbefales.", "pris": "€"},
    {"navn": "Sankt Nikolai, Hamburg", "by": "Sankt Nikolai, Hamburg", "land": "Tyskland", "type": "kultur", "latitude": 53.5475, "longitude": 9.9900, "beskrivelse": "Ruinen av en nygotisk kirke, bombet under andre verdenskrig, nå et minnesmerke mot krig.", "tips": "Ta heisen opp i tårnet for panoramautsikt over Hamburg.", "pris": "€"},
    {"navn": "Vogelsang Ordensburg", "by": "Vogelsang Ordensburg", "land": "Tyskland", "type": "kultur", "latitude": 50.5833, "longitude": 6.4500, "beskrivelse": "Tidligere nazistisk ordensborg i Eifel, senere brukt av britene og belgierne som militærbase.", "tips": "Utstillingen 'Bestimmung: Herrenmensch' er svært grundig.", "pris": "€"},
    {"navn": "Project Riese", "by": "Project Riese", "land": "Polen", "type": "kultur", "latitude": 50.6833, "longitude": 16.4167, "beskrivelse": "Et enormt, uferdig nazistisk tunnelkompleks i Uglefjellene, bygget av tvangsarbeidere.", "tips": "Ta med lommelykt og gode sko – tunnelene er mørke og ujevne.", "pris": "€"},
    {"navn": "Kaplica Czaszek", "by": "Kaplica Czaszek", "land": "Polen", "type": "kultur", "latitude": 50.5833, "longitude": 16.3333, "beskrivelse": "En skjelettkirke dekorert med hodeskaller og bein fra over 3000 mennesker.", "tips": "Kombiner med en tur til den nærliggende festningen i Kłodzko.", "pris": "€"},
    {"navn": "Wilcze Gardło", "by": "Wilcze Gardło", "land": "Polen", "type": "kultur", "latitude": 54.0000, "longitude": 21.1333, "beskrivelse": "Tysk ulvehule fra andre verdenskrig, skjult i skogene i Masuria.", "tips": "Guidet tur gir best innsikt i historien.", "pris": "€"},
    {"navn": "Palais Idéal", "by": "Palais Idéal", "land": "Frankrike", "type": "kultur", "latitude": 45.2667, "longitude": 4.7500, "beskrivelse": "Et eventyrlig, naivistisk palass bygget for hånd av postbudet Ferdinand Cheval over 33 år.", "tips": "Kom tidlig for å unngå kø – det er populært.", "pris": "€"},
    # ========== SÆRPREGEDE REISEMÅL ==========
    {"navn": "Bilkirkegården i Båstnäs", "land": "Sverige", "by": "Töcksfors", "type": "kultur", "latitude": 59.3615, "longitude": 11.8422, "beskrivelse": "Skogområde ved grensen der hundrevis av eldre biler står igjen som et uvanlig møte mellom industrihistorie og natur.", "tips": "Bruk solide sko og hold deg på tydelige stier mellom de rustne kjøretøyene.", "pris": "€"},
    {"navn": "Nordstrandischmoor", "land": "Tyskland", "by": "Nordstrand", "type": "kultur", "latitude": 54.5502, "longitude": 8.8118, "beskrivelse": "Hallig i Vadehavet der adkomst ofte skjer via smal skinnegående transport over tidevannssletter.", "tips": "Planlegg etter tidevannstabeller og lokale avgangstider.", "pris": "€"},
    {"navn": "Automuseum Melle", "land": "Tyskland", "by": "Melle", "type": "kultur", "latitude": 52.2031, "longitude": 8.3414, "beskrivelse": "Privat bilsamling i Niedersachsen med kjørende veteranbiler, verkstedsstemning og temautstillinger utenfor de store merkevare-museene.", "tips": "Sjekk om det er kjøredag eller spesialevent — da er samlingen mest levende.", "pris": "€"},
    {"navn": "Worpswede", "land": "Tyskland", "by": "Worpswede", "type": "kultur", "latitude": 53.2217, "longitude": 8.9267, "beskrivelse": "Kjent kunstnerkoloni i Nord-Tyskland med gallerier, atelierer og sterk tilknytning til ekspresjonismen.", "tips": "Besøk Barkenhoff og de mindre galleriene i sentrum.", "pris": "€"},
    {"navn": "Mumienkeller Bleicherode", "land": "Tyskland", "by": "Bleicherode", "type": "kultur", "latitude": 51.4402, "longitude": 10.5714, "beskrivelse": "Historisk hvelv med naturlig mumifiserte levninger, knyttet til lokal gravskikk og kirkehistorie.", "tips": "Sjekk åpningstider på forhånd, da tilgang kan være begrenset.", "pris": "€"},
    {"navn": "Doruchów", "land": "Polen", "by": "Doruchów", "type": "kultur", "latitude": 51.4172, "longitude": 18.0694, "beskrivelse": "Liten landsby i Wielkopolska med minnesmerke og utstilling om hekseprosessene på 1700-tallet, et sjeldnere historisk tema i Polen.", "tips": "Les infotavlene på stedet og kombiner med museum i nærliggende byer for mer kontekst.", "pris": "€"},
    {"navn": "Bolwoningen", "land": "Nederland", "by": "'s-Hertogenbosch", "type": "kultur", "latitude": 51.7183, "longitude": 5.3377, "beskrivelse": "Eksperimentelt boligområde med kuleformede hus fra 1980-tallet, kjent for særegen urban arkitektur.", "tips": "Gå området til fots for å få best inntrykk av formene og planløsningen.", "pris": "€"},
    {"navn": "CasAnus", "land": "Belgia", "by": "Kemzeke", "type": "kultur", "latitude": 51.2075, "longitude": 4.0674, "beskrivelse": "Skulpturelt kunstprosjekt med overnatting i et uvanlig byggverk, skapt som en blanding av kunst og installasjon.", "tips": "Bestill i god tid hvis du ønsker overnatting, siden kapasiteten er svært begrenset.", "pris": "€"},
    {"navn": "Blowing Stone", "land": "Storbritannia", "by": "Shrivenham", "type": "kultur", "latitude": 51.5714, "longitude": -1.5684, "beskrivelse": "Historisk perforert stein knyttet til lokal folklore, kjent for den kraftige tonen man kan lage ved å blåse i åpningen.", "tips": "Ta med vannflaske og utforsk området rundt White Horse Hill samtidig.", "pris": "€"},
    {"navn": "Lea & Perrins", "land": "Storbritannia", "by": "Worcester", "type": "kultur", "latitude": 52.1936, "longitude": -2.2144, "beskrivelse": "Historisk produksjonssted for den klassiske Worcestersausen, med lokal mat- og industrikultur i sentrum.", "tips": "Kombiner med en matvandring i Worcester sentrum.", "pris": "€"},
    {"navn": "Whitstable", "land": "Storbritannia", "by": "Whitstable", "type": "kultur", "latitude": 51.3607, "longitude": 1.0257, "beskrivelse": "Kystby i Kent kjent for østers, små sjømatrestauranter og tradisjonell britisk havneatmosfære.", "tips": "Kom tidlig for ferskeste sjømat ved havnen.", "pris": "€€"},
    {"navn": "Isle of Man", "land": "Storbritannia", "by": "Peel", "type": "kultur", "latitude": 54.2219, "longitude": -4.6908, "beskrivelse": "Selvstyrt øysamfunn i Irskesjøen med særegen motorkultur, maritime tradisjoner og flere små spesialmuseer.", "tips": "Lei bil eller sykkel for å se mer enn kun Peel-området.", "pris": "€"},
    # ========== HÅNDPLUKKEDE SKJULTE PERLER: ITALIA ==========
    {"navn": "Calcata Vecchia", "land": "Italia", "by": "Calcata", "type": "kunstnerlandsby", "beskrivelse": "En dramatisk middelalderlandsby på en tuffklippe nord for Roma, reddet av kunstnere, håndverkere og bohemer etter at den nesten ble fraflyttet.", "tips": "Kom på en ukedag og gå innom de små atelierene før solnedgang over Treja-dalen.", "beste_tid": "mars-juni, september-november", "latitude": 42.2195, "longitude": 12.4257, "pris": "€€"},
    {"navn": "Dozza", "land": "Italia", "by": "Dozza", "type": "gatekunst", "beskrivelse": "En liten befestet landsby i Emilia-Romagna der husveggene er dekket av store kunstverk og hele sentrum fungerer som et åpent galleri.", "tips": "Kombiner muralvandring med vinsmaking i Enoteca Regionale under borgen.", "beste_tid": "april-oktober", "latitude": 44.3608, "longitude": 11.6286, "pris": "€€"},
    {"navn": "Santo Stefano di Sessanio", "land": "Italia", "by": "Santo Stefano di Sessanio", "type": "fjellandsby", "beskrivelse": "En nesten forlatt steinlandsby høyt i Abruzzo, langsomt restaurert til et atmosfærisk albergo diffuso omgitt av fjell og sauebeiter.", "tips": "Bo i et restaurert steinhus og kjør videre til Campo Imperatore ved daggry.", "beste_tid": "mai-oktober", "latitude": 42.3436, "longitude": 13.6447, "pris": "€€"},
    {"navn": "Bussana Vecchia", "land": "Italia", "by": "Sanremo", "type": "kunstnerkoloni", "beskrivelse": "En jordskjelvødelagt ligurisk landsby som ble tatt tilbake av kunstnere på 1960-tallet, med ruiner, gallerier og frodige smug.", "tips": "Gå hit tidlig fra Bussana Nuova og spis lunsj i en av de skjulte gårdsrommene.", "beste_tid": "mars-juni, september-oktober", "latitude": 43.8371, "longitude": 7.8280, "pris": "€€"},
    {"navn": "Vitorchiano", "land": "Italia", "by": "Vitorchiano", "type": "middelalderby", "beskrivelse": "En kompakt steinby i Lazio bygget på vulkansk klippe, med smale passasjer, hengende hager og en uventet Moai-statue.", "tips": "Følg stien ned under bymuren for det beste perspektivet på klippebyen.", "beste_tid": "april-juni, september-november", "latitude": 42.4655, "longitude": 12.1712, "pris": "€"},
    # ========== HÅNDPLUKKEDE SKJULTE PERLER: SPANIA ==========
    {"navn": "Albarracín", "land": "Spania", "by": "Albarracín", "type": "middelalderby", "beskrivelse": "Rosa-rød fjellby i Aragón med skjeve hus, bymurer og labyrintiske smug som føles som en filmkulisse uten kystturismen.", "tips": "Gå bymurene rett før solnedgang og overnatt for å få byen nesten alene.", "beste_tid": "april-juni, september-oktober", "latitude": 40.4083, "longitude": -1.4430, "pris": "€€"},
    {"navn": "Mallos de Riglos", "land": "Spania", "by": "Riglos", "type": "natur", "beskrivelse": "En liten landsby presset inn under enorme røde konglomeratklipper, kjent blant klatrere men ofte oversett av vanlige reisende.", "tips": "Ta rundløypa Camino del Cielo for utsikt mot gribber, klipper og landsbyen.", "beste_tid": "mars-juni, september-november", "latitude": 42.3486, "longitude": -0.7278, "pris": "€"},
    {"navn": "Frías", "land": "Spania", "by": "Frías", "type": "historie", "beskrivelse": "En av Spanias minste byer, balansert på en kalksteinsrygg med hengende hus, borg og en middelalderbro over Ebro.", "tips": "Kombiner med Tobera-fossene og kom om morgenen før dagsbesøkende.", "beste_tid": "april-oktober", "latitude": 42.7625, "longitude": -3.2933, "pris": "€"},
    {"navn": "Bardenas Reales", "land": "Spania", "by": "Arguedas", "type": "ørkenlandskap", "beskrivelse": "Et halvtørt månelandskap i Navarra med leirformasjoner, raviner og støvete veier som føles mer Arizona enn Nord-Spania.", "tips": "Kjør ruten rundt Castildetierra tidlig eller sent for dramatisk lys og mindre varme.", "beste_tid": "mars-juni, september-november", "latitude": 42.1889, "longitude": -1.5150, "pris": "€"},
    {"navn": "Ujué", "land": "Spania", "by": "Ujué", "type": "pilegrimsby", "beskrivelse": "En liten navarrisk åsby med festningskirke, steinhus og vid utsikt mot Pyreneene og vinmarkene.", "tips": "Prøv migas eller mandelkaker etter besøket i Santa María de Ujué.", "beste_tid": "april-juni, september-oktober", "latitude": 42.5058, "longitude": -1.4992, "pris": "€"},
    # ========== HÅNDPLUKKEDE SKJULTE PERLER: FRANKRIKE ==========
    {"navn": "Conques", "land": "Frankrike", "by": "Conques-en-Rouergue", "type": "pilegrimsby", "beskrivelse": "En kompakt middelalderlandsby i Aveyron med romansk klosterkirke, brosteinsgater og gyllent kveldslys over skifertak.", "tips": "Bli til etter at pilegrimene har gått videre og se Soulages-vinduene i kirken.", "beste_tid": "april-juni, september-oktober", "latitude": 44.5990, "longitude": 2.3971, "pris": "€€"},
    {"navn": "La Couvertoirade", "land": "Frankrike", "by": "La Couvertoirade", "type": "tempelridderlandsby", "beskrivelse": "En befestet landsby på Larzac-platået, knyttet til tempelriddere og hospitalriddere, med intakte murer og vindpisket steinlandskap.", "tips": "Gå utenfor murene for å se byen ligge som en steinfestning i det åpne landskapet.", "beste_tid": "mai-oktober", "latitude": 43.9130, "longitude": 3.3169, "pris": "€"},
    {"navn": "Moustiers-Sainte-Marie", "land": "Frankrike", "by": "Moustiers-Sainte-Marie", "type": "fjellandsby", "beskrivelse": "En provençalsk landsby under kalksteinsklipper, kjent for keramikk og en gullstjerne som henger i lenke mellom fjellveggene.", "tips": "Gå opp til kapellet Notre-Dame de Beauvoir før lunsj og fortsett til Verdon-juvet.", "beste_tid": "april-juni, september-oktober", "latitude": 43.8467, "longitude": 6.2215, "pris": "€€"},
    {"navn": "Saint-Cirq-Lapopie", "land": "Frankrike", "by": "Saint-Cirq-Lapopie", "type": "kunstnerlandsby", "beskrivelse": "En dramatisk landsby høyt over Lot-elven, elsket av surrealister og full av steinhus, trapper og utsiktspunkter.", "tips": "Gå slepestien Chemin de Halage langs elven for en roligere opplevelse.", "beste_tid": "april-juni, september-oktober", "latitude": 44.4658, "longitude": 1.6706, "pris": "€€"},
    {"navn": "Salins-les-Bains", "land": "Frankrike", "by": "Salins-les-Bains", "type": "industrihistorie", "beskrivelse": "En undervurdert kur- og saltby i Jura med underjordiske saltgallerier, termalbad og bratte kalksteinsfort rundt dalen.", "tips": "Besøk Grande Saline og ta deretter kabelbanen eller stien opp til Fort Saint-André.", "beste_tid": "mai-oktober", "latitude": 46.9406, "longitude": 5.8778, "pris": "€€"},
    # ========== HÅNDPLUKKEDE SKJULTE PERLER: TYSKLAND ==========
    {"navn": "Monschau", "land": "Tyskland", "by": "Monschau", "type": "bindingsverksby", "beskrivelse": "En trang dalby i Eifel med mørke bindingsverkshus, brosteinsgater og sennepsmølle, langt roligere enn de store romantiske rutene.", "tips": "Gå opp til utsiktspunktet over Rotes Haus før du besøker sennepsmøllen.", "beste_tid": "april-juni, september-desember", "latitude": 50.5545, "longitude": 6.2400, "pris": "€€"},
    {"navn": "Lüneburg", "land": "Tyskland", "by": "Lüneburg", "type": "hanseatisk kultur", "beskrivelse": "En tidligere saltby med skjeve mursteinsfasader, smug og havnekanter som gir ekte nordtysk atmosfære uten Hamburg-tempoet.", "tips": "Se de skjeve husene i Senkungsgebiet og avslutt ved Stintmarkt.", "beste_tid": "april-oktober", "latitude": 53.2464, "longitude": 10.4115, "pris": "€€"},
    {"navn": "Bastei ved soloppgang", "land": "Tyskland", "by": "Rathen", "type": "natur", "beskrivelse": "Sandsteinstårn og broer i Sächsische Schweiz, spektakulært kjent lokalt men fortsatt magisk hvis du kommer før turistbussene.", "tips": "Overnatt i Rathen og gå opp før frokost for tåke over Elben.", "beste_tid": "april-juni, september-oktober", "latitude": 50.9669, "longitude": 14.0656, "pris": "€"},
    {"navn": "Quedlinburg bakgatene", "land": "Tyskland", "by": "Quedlinburg", "type": "unesco", "beskrivelse": "UNESCO-by med over tusen bindingsverkshus, men de beste opplevelsene ligger i de stille smugene vekk fra markedsplassen.", "tips": "Gå til Münzenberg-kvartalet for små hus, utsikt og færre folk.", "beste_tid": "april-oktober, desember", "latitude": 51.7884, "longitude": 11.1416, "pris": "€€"},
    {"navn": "Völklinger Hütte", "land": "Tyskland", "by": "Völklingen", "type": "industriarv", "beskrivelse": "Et enormt nedlagt jernverk i Saarland, nå UNESCO-sted med gangbroer, rust, kunstutstillinger og nesten sci-fi-aktig industriarkitektur.", "tips": "Sett av minst tre timer og gå opp på de høye plattformene for full effekt.", "beste_tid": "hele året", "latitude": 49.2494, "longitude": 6.8442, "pris": "€€"},
    # ========== HÅNDPLUKKEDE SKJULTE PERLER: POLEN ==========
    {"navn": "Zalipie", "land": "Polen", "by": "Zalipie", "type": "folkekunst", "beskrivelse": "En landsby der hus, brønner og fjøs er dekorert med håndmalte blomster, en levende folkekunsttradisjon langt fra storbyrutene.", "tips": "Start ved Dom Malarek og gå videre mellom gårdene til fots eller på sykkel.", "beste_tid": "mai-september", "latitude": 50.2356, "longitude": 20.8622, "pris": "€"},
    {"navn": "Srebrna Góra festning", "land": "Polen", "by": "Srebrna Góra", "type": "festning", "beskrivelse": "En massiv prøyssisk fjellfestning i Nedre Schlesien, bygget som et militært monster over skogkledde åser.", "tips": "Ta guidet tur i kasemattene og kombiner med utsikten fra Donjon.", "beste_tid": "april-oktober", "latitude": 50.5700, "longitude": 16.6425, "pris": "€"},
    {"navn": "Książ slottets tunneler", "land": "Polen", "by": "Wałbrzych", "type": "mysterie", "beskrivelse": "Et eventyrslott over en ravine med et mørkere lag under bakken, knyttet til nazistenes uferdige Project Riese.", "tips": "Velg billett som inkluderer underjordisk rute, ikke bare slottsrommene.", "beste_tid": "hele året", "latitude": 50.8422, "longitude": 16.2920, "pris": "€€"},
    {"navn": "Tykocin", "land": "Polen", "by": "Tykocin", "type": "jødisk historie", "beskrivelse": "En liten Podlasie-by med barokk torg, bevart synagoge og tung, viktig historie i et landskap få turister prioriterer.", "tips": "Besøk synagogen og spis regional mat før du drar videre mot Biebrza-myrene.", "beste_tid": "mai-september", "latitude": 53.2056, "longitude": 22.7742, "pris": "€"},
    {"navn": "Błędówørkenen", "land": "Polen", "by": "Klucze", "type": "ørkenlandskap", "beskrivelse": "Europas merkeligste innlandsørkenfølelse: sandflater og furuskog i Schlesien, en surreal kontrast til regionens industribyer.", "tips": "Start ved utsiktspunktet Czubatka og kom i gyllent kveldslys.", "beste_tid": "april-oktober", "latitude": 50.3361, "longitude": 19.5567, "pris": "€"},
]

# ========================================
# SPANIA – kuratert markedspakke for nordmenn (Costa Blanca, Andalucía m.m.)
# type = profilinteresse; normaliseres til DB-kategori i data_store
# ========================================
SPANIA_MARKEDSDATA = [
    {
        "id": "es_gem_01",
        "navn": "Setenil de las Bodegas",
        "by": "Ronda/Cádiz",
        "land": "Spania",
        "country_code": "ES",
        "type": "Kultur & Historie",
        "latitude": 36.8639,
        "longitude": -5.1812,
        "beskrivelse": "En helt unik hvit landsby hvor husene er bygget direkte inn under massive overhengende klipper. Fjellet fungerer som naturlig beskyttelse mot solen.",
        "tips": "Gå ned i gaten 'Cuevas del Sol' for å sitte under fjellet.",
        "beste_tid": "Vår og høst.",
        "pris": "€",
    },
    {
        "id": "es_gem_02",
        "navn": "El Castell de Guadalest",
        "by": "Alicante (Baklandet)",
        "land": "Spania",
        "country_code": "ES",
        "type": "Natur & Aktivitet",
        "latitude": 38.6772,
        "longitude": -0.1981,
        "beskrivelse": "En dramatisk festningslandsby tilgjengelig via en uthugget tunnel i fjellet, med utsikt over en smaragdgrønn innsjø.",
        "tips": "Perfekt dagsutflukt fra Costa Blanca. Kom tidlig.",
        "beste_tid": "September til mai.",
        "pris": "€",
    },
    {
        "id": "es_gem_04",
        "navn": "Altea gamleby",
        "by": "Altea",
        "land": "Spania",
        "country_code": "ES",
        "type": "Kultur & Historie",
        "latitude": 38.5992,
        "longitude": -0.0519,
        "beskrivelse": "Hvitkalkede gater, blå kuppeltak og kunstneratelierer på en ås over Costa Blanca – roligere enn Benidorm, men like lett tilgjengelig for nordmenn.",
        "tips": "Gå opp til Iglesia de Nuestra Señora del Consuelo ved solnedgang.",
        "beste_tid": "April til juni og september til november.",
        "pris": "€",
    },
    {
        "id": "es_rest_01",
        "navn": "Venta El Túnel",
        "by": "Málaga",
        "land": "Spania",
        "country_code": "ES",
        "type": "Mat & Vin",
        "latitude": 36.7812,
        "longitude": -4.4214,
        "beskrivelse": "Legendarisk venta i Montes de Málaga siden 1953 – kjent for caldoso-arroz, migas og serrano-retter i skogrike omgivelser, langt fra kystens køer.",
        "tips": "Bestill på forhånd i helgene og prøv arroz con pollo caldoso.",
        "beste_tid": "Hele året.",
        "pris": "€€",
    },
]

LOKALE_SPISESTEDER = [
    {"navn": "Pelikan", "land": "Sverige", "by": "Stockholm", "type": "husmannskost", "beskrivelse": "Husmannskost siden 1664.", "pris": "150-250 SEK", "latitude": 59.3108, "longitude": 18.0792},
    {"navn": "Lilla Ego", "land": "Sverige", "by": "Stockholm", "type": "nordisk", "beskrivelse": "Populær liten restaurant med moderne nordisk mat og tett kontakt mellom kjøkken og gjester.", "pris": "200-400 SEK", "latitude": 59.3444, "longitude": 18.0469},
    {"navn": "Bakfickan", "land": "Sverige", "by": "Stockholm", "type": "husmannskost", "beskrivelse": "Operakjellerens bakside.", "pris": "150-300 SEK", "latitude": 59.3303, "longitude": 18.0703},
    {"navn": "Kaffestuggu", "land": "Norge", "by": "Røros", "type": "kafé", "beskrivelse": "Rømmegrøt i historisk miljø.", "pris": "100-200 NOK", "latitude": 62.5746, "longitude": 11.3853},
    {"navn": "Schønnemann", "land": "Danmark", "by": "København", "type": "smørrebrød", "beskrivelse": "Smørrebrød siden 1877.", "pris": "100-200 DKK", "latitude": 55.6833, "longitude": 12.5739},
    {"navn": "Neckarmüller", "land": "Tyskland", "by": "Tübingen", "type": "tysk", "beskrivelse": "Bryggeri ved Neckar.", "pris": "€10-20", "latitude": 48.5197, "longitude": 9.0583},
    {"navn": "Schlenkerla", "land": "Tyskland", "by": "Bamberg", "type": "tysk", "beskrivelse": "Røykøl siden 1405.", "pris": "€8-15", "latitude": 49.8917, "longitude": 10.8847},
    {"navn": "Zur Letzten Instanz", "land": "Tyskland", "by": "Berlin", "type": "tysk", "beskrivelse": "Berlins eldste. 1621.", "pris": "€15-30", "latitude": 52.5164, "longitude": 13.4147},
    {"navn": "Konnopke's Imbiss", "land": "Tyskland", "by": "Berlin", "type": "streetfood", "beskrivelse": "Klassisk snackbar under U-Bahn-sporene i Prenzlauer Berg, kjent for currywurst i enkel, lokal stil.", "pris": "€3-5", "latitude": 52.5414, "longitude": 13.4119},
    {"navn": "Café Central", "land": "Østerrike", "by": "Wien", "type": "kafé", "beskrivelse": "Grand kafé i Wien fra 1876 med jugendstil, kaker og historisk atmosfære — et klassisk stop, men fortsatt verdt for arkitekturen.", "tips": "Velg forrmiddag fremfor lunsjtime for kortere ventetid.", "pris": "€8-15", "latitude": 48.2103, "longitude": 16.3654},
    {"navn": "Gmoakeller", "land": "Østerrike", "by": "Wien", "type": "østerriksk", "beskrivelse": "Rustikk vinkjeller i Wien med tunge, tradisjonelle retter og lokal vin i en uformell, gammeldags setting.", "tips": "Book bord — få sitteplasser og høy etterspørsel.", "pris": "€15-25", "latitude": 48.2017, "longitude": 16.3789},
    {"navn": "Koliba U Deda", "land": "Slovakia", "by": "Martin", "type": "slovakisk", "beskrivelse": "Tradisjonell slovakisk koliba i Martin-området med brynjica, bryst og andre retter fra fjelltradisjonen.", "tips": "Del en stor tallerken hvis dere er flere — porsjonene er ofte generøse.", "pris": "€5-12", "latitude": 49.0614, "longitude": 18.9167},
    {"navn": "Café Veronský dom", "land": "Slovakia", "by": "Martin", "type": "kafé", "beskrivelse": "Kafé i historisk bygg i Martin med hjemmebakt kaker og rolig atmosfære, et lite pausepunkt mellom fjellturer.", "tips": "Kombiner med besøk i museumsområdet i sentrum.", "pris": "€3-6", "latitude": 49.0681, "longitude": 18.9222},
    {"navn": "Casa Tomis", "land": "Romania", "by": "Constanța", "type": "sjømat", "beskrivelse": "Lokal sjømatrestaurant ved Svartehavskysten med fokus på fersk fisk og enkel, tradisjonell tilberedning.", "tips": "Spør hva som kom inn fra fiskeri samme dag.", "pris": "€8-20", "latitude": 44.1714, "longitude": 28.6606},
    {"navn": "Crama Sibiul Vechi", "land": "Romania", "by": "Sibiu", "type": "rumensk", "beskrivelse": "Historisk vinkjeller i Sibius gamleby med steinvault, lokale viner og tradisjonell rumensk mat.", "tips": "Bestill bord i underetasjen for best stemning.", "pris": "€8-15", "latitude": 45.7958, "longitude": 24.1506},
    {"navn": "Caru' cu Bere", "land": "Romania", "by": "Bukarest", "type": "rumensk", "beskrivelse": "Ikonisk ølhall i Bukarest fra 1879 med jugendstil-interiør, live musikk og klassisk rumensk husmannskost.", "tips": "Reserver bord til kvelds under helg — stedet fylles raskt.", "pris": "€10-25", "latitude": 44.4322, "longitude": 26.0981},
    {"navn": "Café Louvre", "land": "Tsjekkia", "by": "Praha", "type": "kafé", "beskrivelse": "Historisk kafé i Praha fra 1902, kjent som møtested for intellektuelle og fortsatt populært for brunch og kaker.", "tips": "Kom til frokost på ukedag for kortere kø.", "pris": "€5-10", "latitude": 50.0822, "longitude": 14.4186},
    {"navn": "Hanácká Hospoda", "land": "Tsjekkia", "by": "Olomouc", "type": "tsjekkisk", "beskrivelse": "Tradisjonell pub i Olomouc som serverer Olomouc-osten — en skarp, lokalt kjent spesialitet.", "tips": "Prøv osten med øl fra regionen, ikke som en generell «stinky cheese»-gimmick.", "pris": "€5-10", "latitude": 49.5947, "longitude": 17.2522},
    {"navn": "New York Café", "land": "Ungarn", "by": "Budapest", "type": "kafé", "beskrivelse": "Verdens vakreste.", "pris": "€10-20", "latitude": 47.5025, "longitude": 19.0733},
    {"navn": "Bors GasztroBár", "land": "Ungarn", "by": "Budapest", "type": "streetfood", "beskrivelse": "Liten streetfood-bar kjent for kreative supper og baguetter med ungarsk preg.", "pris": "€3-6", "latitude": 47.5014, "longitude": 19.0642},
    {"navn": "Bodega de la Ardosa", "land": "Spania", "by": "Madrid", "type": "tapas", "beskrivelse": "Historisk tapasbar i Madrid fra 1892, kjent for tortilla og stående servering i et klassisk malaga-inspirert lokale.", "tips": "Bestill tortilla de patatas tidlig — den blir ofte utsolgt.", "pris": "€5-15", "latitude": 40.4239, "longitude": -3.7025},
    {"navn": "El Rinconcillo", "land": "Spania", "by": "Sevilla", "type": "tapas", "beskrivelse": "Sevillas eldste bar (siden 1670) med sjarmerende, travel atmosfære og klassiske andalusiske tapas.", "tips": "Skriv bestillingen på disken — det er fortsatt del av ritualer her.", "pris": "€5-15", "latitude": 37.3931, "longitude": -5.9886},
    {"navn": "La Favorita", "land": "Italia", "by": "Bologna", "type": "italiensk", "beskrivelse": "Familiedrevet trattoria i Bologna der dagens rett bestemmes av kjøkkenet — ingen fast meny, sterkt lokalt preg.", "tips": "Spør hva de anbefaler i dag og bestill tidlig.", "pris": "€15-25", "latitude": 44.4939, "longitude": 11.3428},
    {"navn": "Trattoria da Enzo", "land": "Italia", "by": "Roma", "type": "italiensk", "beskrivelse": "Tradisjonell trattoria i Trastevere med romerske klassikere og liten, travel servering.", "pris": "€15-25", "latitude": 41.8881, "longitude": 12.4786},
    {"navn": "All'Arco", "land": "Italia", "by": "Roma", "type": "streetfood", "beskrivelse": "Liten vinbar i Roma med ferske cicchetti, ståplass ved disken og lokalt publikum utenfor de største turistgatene.", "tips": "Kom rett etter åpning for best utvalg av småretter.", "pris": "€5-10", "latitude": 41.8902, "longitude": 12.4922},
    {"navn": "À la Mort Subite", "land": "Belgia", "by": "Brussel", "type": "kafé", "beskrivelse": "Historisk ølkafé.", "pris": "€5-12", "latitude": 50.8483, "longitude": 4.3564},
    {"navn": "The George Inn", "land": "Storbritannia", "by": "London", "type": "pub", "beskrivelse": "Shakespeare drakk her.", "pris": "£10-20", "latitude": 51.5042, "longitude": -0.0911},
    {"navn": "Kehoe's Pub", "land": "Irland", "by": "Dublin", "type": "pub", "beskrivelse": "Urørt siden 1800.", "pris": "€10-20", "latitude": 53.3417, "longitude": -6.2592},
    {"navn": "Tima-Irma", "land": "Bosnia", "by": "Mostar", "type": "bosnisk", "beskrivelse": "Familiedrevet restaurant i Mostar med cevapi, baklava og utsikt mot Neretva — en klassiker blant lokalkjente.", "tips": "Sett deg ute hvis været er fint og du vil se elven.", "pris": "€5-10", "latitude": 43.3369, "longitude": 17.8153}
]

# ========================================
# UNIK OVERNATTING (hotell, hytte, fyr, grotte, prestegård, …)
# ========================================
UNIKE_OVERNATTING = [
    {
        "navn": "Gruvsviten – Sala silvergruva",
        "land": "Sverige",
        "by": "Sala",
        "type": "overnatting",
        "beskrivelse": "Hotellsuite 155 meter under bakken i en av verdens best bevarte gruver. Oppvarmet rom ved mystiske gruvesjøer og underjordiske ganger.",
        "tips": "Ta med varme klær til gruvegangene; rommet er oppvarmet.",
        "beste_tid": "hele året",
        "pris": "ca. 280 € dobbeltrom",
        "latitude": 59.9075,
        "longitude": 16.5702,
    },
    {
        "navn": "CasAnus",
        "land": "Belgia",
        "by": "Kemzeke",
        "type": "overnatting",
        "beskrivelse": "Kunstinstallasjon og overnatting i et uvanlig skulpturelt bygg — en av Europas mest særegne overnattingsopplevelser.",
        "tips": "Bestill langt i forvegen; svært begrenset kapasitet.",
        "beste_tid": "april-oktober",
        "pris": "ca. 95 € dobbeltrom",
        "latitude": 51.2075,
        "longitude": 4.0674,
    },
    {
        "navn": "Borgvattnets Prästgård",
        "land": "Sverige",
        "by": "Borgvattnet",
        "type": "overnatting",
        "beskrivelse": "Historisk prestegård i Jämtland med overnatting og rykte som et av Sveriges mest omtalte «hemsökta» steder.",
        "tips": "Book overnatting på forhånd om du vil være der etter åpningstid.",
        "beste_tid": "hele året",
        "pris": "ca. 120 € dobbeltrom",
        "latitude": 63.4211,
        "longitude": 15.8544,
    },
    {
        "navn": "Fyrvokterboligen Bjuröklubb",
        "land": "Sverige",
        "by": "Lövånger",
        "type": "overnatting",
        "beskrivelse": "Overnatting i fyrvokterbolig på en utsatt odde ved Bottenviken — kveld og morgen med hav og svaberg nesten for deg selv.",
        "tips": "Sesongbasert; sjekk tilgjengelighet for sommer.",
        "beste_tid": "juni-juli",
        "pris": "ca. 180 € dobbeltrom",
        "latitude": 64.4811,
        "longitude": 21.5714,
    },
    {
        "navn": "Sassi-grottehotell i Matera",
        "land": "Italia",
        "by": "Matera",
        "type": "overnatting",
        "beskrivelse": "Overnatt i huleboliger og steinarkitektur i UNESCO-området Sassi — opplev byen når turistene har gått.",
        "tips": "Velg sertifisert grottehotell i Sassi; kombiner med kveldsvandring.",
        "beste_tid": "april-oktober",
        "pris": "140-250 € dobbeltrom",
        "latitude": 40.6667,
        "longitude": 16.6000,
    },
    {
        "navn": "Portmeirion Village",
        "land": "Storbritannia",
        "by": "Portmeirion",
        "type": "overnatting",
        "beskrivelse": "Overnatt i den planlagte «italienske» landsbyen i Wales — hotell og hus midt i et unikt designlandskap.",
        "tips": "Book rom i landsbyen for åpningstid uten dagsturister.",
        "beste_tid": "mai-september",
        "pris": "200-290 € dobbeltrom",
        "latitude": 52.9133,
        "longitude": -4.0994,
    },
    {
        "navn": "Hotel Quadrille",
        "land": "Polen",
        "by": "Gdynia",
        "type": "overnatting",
        "beskrivelse": "Voksenhotell i restaurert 1700-tallspalé med Alice i Eventyrland-tema — et av få Relais & Châteaux-hotell i Polen, langt fra kjedene i Tri-byen.",
        "tips": "Velg et av forfatternavn-rommene og avslutt med tastingmeny på White Rabbit Restaurant i parken.",
        "beste_tid": "mai-september",
        "pris": "ca. 280 € dobbeltrom",
        "latitude": 54.481090,
        "longitude": 18.540057,
    },
]

# Bakoverkompatibilitet (eldre imports: from database import UNIKE_HOTELLER)
UNIKE_HOTELLER = UNIKE_OVERNATTING

__all__ = [
    "SKJULTE_PERLER",
    "LOKALE_SPISESTEDER",
    "SPANIA_MARKEDSDATA",
    "UNIKE_OVERNATTING",
    "UNIKE_HOTELLER",
]